src/parse.c
tests/generate.py

It gets very difficult if we use a single function to handle both the
bridge and bond case, so for the sake of simplicity I duplicated the
function.
LP: #1748057
I've also switched to strduping the interface name rather than using
references which just makes parsing a little more robust against things
failing part way through.
Signed-off-by: Daniel Axtens <dja@axtens.net>

Do not allow a device to be enslaved to a bridge and bond simultaneously

---

debian/control
src/networkd.c
tests/generate.py

As discussed on IRC, optional=true => RequiredForOnline=no
I also noticed when testing this that we need a very recent systemd for this to work, so require that in debian/control, which prevents installing this on e.g. artful where the option has no effect.

Fixup for optional=true

---

netplan/cli/commands/migrate.py
tests/cli.py

This allows migration of most uses of static interfaces:
- IPv4
- IPv6
- setting DNS nameservers and search domains (also for DHCP)
- setting custom MTUs
- setting custom MAC addresses (also for DHCP)
It doesn't support static bonds or bridges because currently there's no support for that at all in ifupdown-migrate.
v2: rebase on top of command-refactor, which was much less painful than I expected!

v2: Support migrating static interfaces from /e/n/i

---

rpm/netplan.spec

This spec file builds Netplan for Fedora and EL7 (with EPEL repositories enabled).
Signed-off-by: Neal Gompa <ngompa13@gmail.com>

Introduce initial RPM spec for packaging

---

doc/netplan.md

dhcp6 is useful for stateful and stateless DHCP.
dhcp6 is also useful to cause an interface to be brought up in a
fully autoconfigured IPv6-only environment, where otherwise the
interface wouldn't be brought up.
Point out that rdnssd is needed for rdnss with networkd.
Signed-off-by: Daniel Axtens <dja@axtens.net>

docs: make dhcp6 more comprehensive

---

doc/netplan.md
src/networkd.c
src/parse.c
src/parse.h
tests/generate.py

Make sure our users who use DHCP server software that doesn't understand
RFC-4361 unique client identifiers can still get the right reservation
behavior. When 'dhcp-identifier: mac' is set, set ClientIdentifier: mac
for systemd-networkd so it does the right thing.
'dhcp-identifier: duid' is valid too, but is the default and thus a noop.

yaml: add dhcp-identifier: field for compatibility with non-RFC4361 things

---

doc/netplan.md
src/networkd.c
src/parse.c
src/parse.h
tests/generate.py

Do not always emit an IPv6AcceptRA value into network configurations.
Systemd-networkd defaults to kernel value as long as the value stays
unset in the configuration.  When IPv6AcceptRA is enabled in systemd
this makes networkd wait 10 seconds for potential RAs to arrive.  This
delays boot by 10 seconds always whether or not the network has an
IPV6 Router running.  Leaving things unsets keeps existing behavior
of Ubuntu systems where RAs are accepted and processed at the time
they are received and boot is not delayed by waiting for an RA to arrive.
If users want to forcibly enable or disable, they may do so by including
a value for accept-ra in their yaml configuraion.
LP: #1732002

accept-ra: do not enable by default, default to unset

---

doc/netplan.md
src/networkd.c
tests/generate.py

Linux kernel bond parameter settings are exclusively in millisecond
units, save lp_interval which is in seconds.  Existing configurations and
documentation indicate values for mii-monitor-interval, arp-interval,
up-delay and down-delay are expressed in milliseconds.  Netplan will render
these values as milliseconds in the networkd backend unless a user has
indicated a different time unit by appending a suffix, like 's' for seconds.
LP: #1765833

bonds: default to milliseconds for unspecified values in intervals

---

src/generate.c

When performing "netplan try" or "netplan apply" on
a network definition with errors, netplan error out
a message as follow :
$ netplan try
Error in network definition //etc/netplan/50-cloud-init.yaml line 6 column 4: unknown key xversion
An error occured: the configuration could not be generated
$ netplan apply
Error in network definition //etc/netplan/50-cloud-init.yaml line 6 column 4: unknown key xversion
That is due to the combination of G_DIR_SEPARATOR_S "/" and "/etc/netplan/*/yaml which once joined
together generate "//etc/netplan/*.yaml".
Bug: https://bugs.launchpad.net/bugs/1771440

Fix double slash in yaml path file

---

Makefile
doc/netplan.md
tests/validate_docs.sh

I went to document the fact that setting the MTU on a device works reliably only if you match by MAC, but found that MTU wasn't documented at all! So I documented it.
The lack of documentation of MTU was a bit of a shock because I just recently attempted to go through and manually check everything was documented. (I documented resend-igmp and optional at that point.) So I was surprised I had missed something so obvious! I decided that therefore it was probably a good idea to do this automatically, so I wrote a shell script that goes through parse.c, extracts keys from mappings and makes sure they're all documented. In the process I caught:
- `mark` being documented as `fwmark` and
- my optional docs being subtly different in format from the rest of the file.
The new check runs during …

Doc fixups and test script

---

doc/netplan.md
examples/static_singlenic_multiip_multigateway.yaml

What was missing in the examples and documentation is a common case when trying to use Ubuntu on VPSes.  VPSes get created with a *single* NIC of which all IP addresses assigned to the VPS can be used on.
For some background though, I have a VPS from RamNode that I was installing 18.04 on, and it has a couple of IPs that are all the same gateway, but a couple IPs which aren't because they go through a different circuit at the same datacenter/host.  This all happens on a single NIC, so setting up this type of setup was not documented in existing examples for Netplan.
In typical `ifupdown` fashion (the "old school" way), you'd have to do some manual `ip addr add` and `ip route add` magic to make it work properly, or you'd have to use NIC aliases (`eno1`, `eno1:1`, etc.) to achieve this. …

Examples and Documentation for one nic, multiple IPs/gateways

---

netplan/cli/commands/try_command.py

The ConfigManager object creates a tempdir upon instatiation, but due to how commands are loaded, the cleanup method isn't called for commands outside of 'try'.  Resolve this by deferring the tmpdir creation by use of @property allowing the first caller of config_manager to trigger the initialization.
LP: #1767464

Defer creation of ConfigManager tmpdir until needed

---

doc/netplan-apply.md
doc/netplan-try.md

No longer need to warn about the side effect of replug.
Fixes: 77ab99dbd420 ("Detect and apply interface naming changes on 'netplan apply'")
Signed-off-by: Daniel Axtens <dja@axtens.net>
- [Y] Runs 'make check' successfully.
- [Y] Retains 100% code coverage (make check-coverage).
- [N/A] New/changed keys in YAML format are documented.
- [N] (Optional) Closes an open bug in Launchpad.

Update man pages for deletion of replug code

---

doc/netplan.md
src/networkd.c
src/nm.c
src/parse.c
src/parse.h
tests/generate.py
tests/validate_docs.sh

[LP: #1756701](https://bugs.launchpad.net/netplan/+bug/1756701)
Throughout the codebase, gratuitous has an extra 'i' (gratuit_i_ous).
This includes the output for networkd. This misspelling causes the
value to have no effect - regardless of the setting, I only see 1
gratuitous ARP in active-backup mode.
It also causes the following message to be printed to syslog:
/run/systemd/network/10-netplan-bond0.netdev:9: Unknown lvalue 'GratuitiousARP' in section 'Bond'
Changing the networkd code to spit out the correct spelling causes
the correct behaviour.
The NM parameter is num_grat_arp, which is not affected by the broader
misspelling. However, NM is affected by a different bug which fixes the
number of gratuitous arps to 1. This has been fixed upstream but not
backported yet: …

Spell Gratuitous ARP correctly and make it work

---

doc/netplan.md
src/networkd.c
src/parse.c
src/parse.h
tests/generate.py

Adds dhcp4-overrides and dhcp6-overrides. These mappings override
specific DHCP behaviors.
Example usage:
```
network:
version: 2
ethernets:
eth0:
dhcp4: yes
dhcp4-overrides:
use-dns: no
```
The available options added in this commit are:
-   `use-dns`
-   `use-ntp`
-   `send-hostname`
-   `use-hostname`
-   `hostname`
This fixes launchpad bug [#1759014](https://bugs.launchpad.net/netplan/+bug/1759014).

Add DHCP behavior override options for networkd.

---

Makefile
rpm/netplan.spec

This PR makes a minor fix to the Makefile to fix `make check` on Fedora, and updates the RPM spec file to properly package the current code.

Fix building netplan on Fedora and update the spec file accordingly

---

netplan/cli/commands/apply.py

The by-mac array should contain the new name (newname variable) instead of the interface ID (phy), so when called in
`new_name = matches['by-mac'][macaddress]` the new name is returned.
Bugs:
https://bugs.launchpad.net/netplan/+bug/1770082
https://bugs.launchpad.net/netplan/+bug/1768827

Fix bug where interface name is wrongly set to ID

---

src/generate.c
src/networkd.c
src/nm.c
src/parse.c
tests/validate_docs.sh

In several places tabs were used for indentation instead of spaces, as is the
majority convention in this project.
Formatting only. No functionality changes.

Replace stray tabs with spaces.

---

netplan/cli/commands/apply.py
tests/integration.py

Fix renaming where interfaces share MAC addresses.
https://bugs.launchpad.net/ubuntu/+source/netplan.io/+bug/1802322

Fix renaming where interfaces share MAC addresses

---

src/generate.c
src/parse.c
src/parse.h

Hello,
I am currently working on a new backend for netplan. This backend will add support for ifupdown2 configuration file generation (https://github.com/CumulusNetworks/ifupdown2/tree/master-next). 
While working on this I faced several challenges. ifupdown2 like other network manager builds its configuration by creating a dependency graph of the desired configuration. 
The goal of this PR is to make sure that the backends are called with netdef according to their dependencies and not iterating through the main netdef hashtable in not specific order. 
After the check list bellow i've added more details and logs to make my case (this is also part of the commit introducing the change). 
I hope that this PR can be accepted before submitting my main PR adding the ifupdown2 backend. I …

Generate output files in dependency order

---

doc/netplan.md
src/networkd.c
src/parse.c
src/parse.h
tests/generator/base.py
tests/generator/test_bonds.py
tests/generator/test_bridges.py
tests/generator/test_common.py
tests/generator/test_dhcp_overrides.py
tests/generator/test_ethernets.py
tests/generator/test_vlans.py
tests/generator/test_wifis.py

Currently, there is no way to override networkd's
UseMTU flag via Netplan. This is useful to have
as a dhcp-override option similar to the other
dhcp-override options.
If the 'use-mtu' key is set to false in the netplan
config file, then set 'UseMTU' as false in networkd's
config.
Signed-off-by: Shashank Ram <shashank08@gmail.com>

Add support to override networkd UseMTU setting

---

src/networkd.c
tests/generator/test_common.py

Some installation services generate netplan configuration that is a little
verbose, including default values for fields that are really optional.
These would potentially be fine, if misguided, if networkd was to do a better
job at matching -- however, it can't really do so, since it's also not given
additional matching criteria.
We're not given that matching criteria either, but while things get sorted
out in the various installation services, attempt to workaround this
scenario by defining the match for this particular case (bonds using the
MAC address of a member phy, defined as such in the config) to try
and catch only the ethernet devices. As those don't have DEVTYPE, do
some further fuzzy matching by excluding vlans, bridges and bonds.
To be clear: IT IS NOT RECOMMENDED to rely on …

networkd: Workaround matching interaction bug with networkd

---

debian/tests/control
doc/netplan.md
src/networkd.c
src/nm.c
src/parse.c
src/parse.h
tests/generator/test_common.py
tests/generator/test_tunnels.py
tests/integration/__init__.py
tests/integration/base.py
tests/integration/tunnels.py
tests/validate_docs.sh

Add support for bringing up various tunnel types:
- gre
- sit
- ipip / ipip6 / ip6ip6
- isatap (NetworkManager only)
- ip6gre
- gretap / ip6gretap (networkd only)
- vti / vti6
- [WIP] Runs `make check` successfully.
- [WIP] Retains 100% code coverage (`make check-coverage`).
- [WIP] New/changed keys in YAML format are documented.
- [WIP] \(Optional\) Closes an open bug in Launchpad.

Tunnel support in networkd/NM backends

---

debian/tests/control
tests/integration/base.py
tests/integration/bonds.py
tests/integration/bridges.py
tests/integration/ethernets.py
tests/integration/regressions.py
tests/integration/routing.py
tests/integration/run.py
tests/integration/scenarios.py
tests/integration/tunnels.py
tests/integration/vlans.py
tests/integration/wifi.py

Just making the integration tests a little easier to run and control.
- [n/a] \(Optional\) Closes an open bug in Launchpad.

integration: create a test runner so our integration tests can be reused

---

doc/netplan.md

The example block in "Properties for device type vlans:" on the "Reference"
site contains a key "address:" which doesn't exist. I suspect the key needed
is "addresses:".
LP: #1811802

doc: update vlan example to use 'addresses' property

---

rpm/netplan.spec

The original Changelog entry of Fri Dec 13 causes a build warning in rpmbuild. Based on the release date of 0.95 I updated the date in the changelog to be Fri Dec 14 which fixes the build warning
ex.
rpmbuild -ba netplan/rpm/netplan.spec 
warning: bogus date in %changelog: Fri Dec 13 2018 Mathieu Trudel-Lapierre <mathieu.trudel-lapierre@canonical.com> - 0.95

Fixed Date in changelog section

---

src/networkd.c
tests/generator/test_dhcp_overrides.py

networkd does not support separate configuration for dhcp4 and dhcp6.
For all other DHCP override options, an appropriate error is produced when the option is set differently for dhcp4 and dhcp6.  When the use-routes DHCP override option was introduced this check was omitted.

Enforce that use-routes is the same for dhcp4 and dhcp6 in networkd backend.

---

netplan/cli/commands/try_command.py

`self.t` is only defined within the `try` block.  If an exception is thrown and the try bails out, `self.t` is undefined.  This causes the `finally` block to throw its own exception when it tries to call `self.t.reset`, and netplan crashes.

Initializing self.t to test before self.t.reset

---

src/nm.c
tests/generator/base.py
tests/generator/test_bridges.py
tests/generator/test_common.py
tests/generator/test_vlans.py

Deal with changes in NM. Fix the tests so .nmconnection isn't mandatory when writing the tests.

Deal with NM 1.15.2's addition of the .nmconnection extension

---

tests/test_terminal.py

test_save, test_save_and_restore_with_dict: Ensure that we restore the
terminal state at the end of each test, as other tests rely on a clean
state to start. Previously, the tests would work the first time but fail
if re-run.
test_save: also compare self.terminal.orig_flags to the current
terminal flags, as opposed to a copy of itself (which would always pass)
Fixes LP: #1817660
- [N/A] New/changed keys in YAML format are documented.

tests/test_terminal.py: Ensure terminal state is restored at end of test

---

Makefile

If "sudo make install"  is run twice in a row, it fails the second time due to existing files. This fixes that.
- [ x] Runs `make check` successfully.
- [ x] Retains 100% code coverage (`make check-coverage`).
- [ x] New/changed keys in YAML format are documented.

Fix failure in make install

---

Makefile
src/error.c
src/error.h
src/generate.c
src/parse.c
src/parse.h
src/validation.c
src/validation.h
tests/generator/test_common.py

Rework renderer parsing and netdef validation to revert commit fe1fac85 and work around the resulting failures in validating tunnels (which have renderer-specific rules). Seems more logical to go about validating in a single pass anyway, once we're sure we do have all the required information.
This would fix https://bugs.launchpad.net/ubuntu/+source/netplan.io/+bug/1825206

Rework renderer parsing / netdef validation

---

.gitignore
Makefile
dbus/io.netplan.Netplan.conf
dbus/io.netplan.Netplan.service.in
src/dbus.c
tests/dbus/test_dbus.py

This PR adds a new io.netplan.Netplan dbus activatable service
that can be used to Apply a netplan configuration.
The main use-case for this is Ubuntu Core where we want to allow
snaps to control the netplan network configuration via an interface.
However we do not want to give access to systemctl to restart
systemd-networkd or network-manager. The dbus service will run
outside of the confinement will archive this goal.
The interface is probably useful beyond Ubuntu Core.

add dbus based "netplan apply" interface

---

Makefile

The generator is compiled and linked in a single command that honors
CFLAGS but not LDFLAGS. To make it easier for packagers, any linking
should honor LDFLAGS, so add them to the command.

Honor LDFLAGS when linking the generator

---

Makefile
tests/generator/base.py
tests/generator/test_args.py
tests/generator/test_auth.py
tests/generator/test_bonds.py
tests/generator/test_bridges.py
tests/generator/test_common.py
tests/generator/test_dhcp_overrides.py
tests/generator/test_errors.py
tests/generator/test_ethernets.py
tests/generator/test_routing.py
tests/generator/test_tunnels.py
tests/generator/test_vlans.py
tests/generator/test_wifis.py

While working on new tests I noticed that the tests in
tests/generator are not checked by pyflakes. This PR fixes this
and also fixes the pyflakes errors.

Makefile: add tests/generator/*.py to PYCODE

---

src/networkd.c
src/nm.c
tests/generator/test_bridges.py
tests/generator/test_vlans.py

Some tests were failing on my system because of a couple of places the
output depended on hashmap order. Fix those to iterate over the more
deterministic netdef_ordered list instead, and fix a couple of tests
that hardcoded a different order.

make output more deterministic and fix tests

---

.gitignore
netplan/cli/commands/apply.py
tests/dbus/test_dbus.py

Continuation of #93 to have the `netplan apply` command use the D-Bus activated service to actually run the privileged version of `netplan apply` outside of snap confinement. After this is merged, we will update the `network-setup-control` interface in snapd to allow calling this D-Bus service so that running `netplan apply` inside a strictly confined snap will result in `netplan apply` really being called outside of confinement. 
I had to reopen this because GitHub wouldn't let me re-open a PR which had the source branch force-pushed (originally was #96).

netplan/apply: use dbus when inside a snap

---

doc/netplan.md
src/networkd.c
src/nm.c
src/parse.c
src/parse.h
tests/generator/test_common.py

Allow configuration of networkd's IPv6MTUBytes. network manager does not appear to allow this to be set except via router advisement.

add support for IPv6MTUBytes

---

doc/netplan.md
src/parse.c
tests/generator/test_bonds.py

This changes adds checks for bond modes to prevent the acceptance of invalid modes or aliases.  For example, supplying `mode: 4` instead of `mode: 802.3ad`
Any existing code coverage that originally handled bonding covers this.
- [* ] Runs `make check` successfully.
- [?] Retains 100% code coverage (`make check-coverage`).
- [N/A] New/changed keys in YAML format are documented.
- [N/A] \(Optional\) Closes an open bug in Launchpad.

Bonding mode validation

---

dbus/io.netplan.Netplan.service.in

This is needed for initial activation via D-Bus from a confined program such as
a snap. See https://github.com/snapcore/snapd/pull/7214#discussion_r314333683 as
well as https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1749000

io.netplan.Netplan.service.in: add assumed apparmor label

---

Makefile

_features.h accidentally includes escape character, escape it in shell.

Makefile: fix escaping in _features.h

---

Makefile

This is a follow-up to #91, not sure how I missed this, sorry about
that.
netplan-dbus is compiled and linked in a single command that honors
CFLAGS but not LDFLAGS. To make it easier for packagers, any linking
should honor LDFLAGS, so add them to the command.
- [x ] Runs `make check` successfully.
- [ x] Retains 100% code coverage (`make check-coverage`).
- [ x] New/changed keys in YAML format are documented.

Honor LDFLAGS when building netplan-dbus

---

src/networkd.c
tests/generator/test_common.py
tests/generator/test_ethernets.py

This will account for virtual devices or cases where running in containers.
Signed-off-by: Mathieu Trudel-Lapierre <mathieu.trudel-lapierre@canonical.com>

networkd: set MTUBytes= in .network files as well

---

doc/netplan.md
src/networkd.c
src/nm.c
src/parse.c
src/parse.h
tests/generator/test_auth.py

For corporate wired 802.1x networks, a common config is PEAP plus an
MSCHAPv2 phase2. This is supported by wpa_supplicant, and NM, but not
netplan. This adds support for that.
Signed-off-by: Phil Dibowitz <phil@ipom.com>

Add `phase2` keyword to `auth` section

---

doc/netplan.md
src/networkd.c
tests/generator/test_common.py

This change allows the `critical` option to be used without `dhcp4` or `dhcp6` also being enabled. My understanding is that the underlying networkd option `CriticalConnection` also can prevent static IPs being dropped, not just ones assigned via DHCP. In my case, I needed to prevent IPs being assigned by keepalived from being dropped.
- [*] Runs `make check` successfully.
- [*] Retains 100% code coverage (`make check-coverage`).
- [*] New/changed keys in YAML format are documented.

Allow `critical` to be used without `dhcp4`/`dhcp6` enabled

---

doc/netplan.md
src/networkd.c
src/nm.c
src/parse.c
src/parse.h
tests/generator/test_gsm.py

This PR adds initial support for GSM modems for the NetworkManager renderer.
It is an update to PR #117 from @cedws

Initial support for GSM modems for NetworkManager backend – 2

---

doc/netplan.md
src/networkd.c
src/parse.c
src/parse.h
tests/generator/test_ethernets.py

It is actually sadly not possible to say to networkd to send lldp packets on its interfaces. This is really useful in a profesional environment.

Add option `emit-lldp` for networkd backend

---

src/networkd.c
tests/generator/test_auth.py
tests/generator/test_wifis.py

Per definition seen on wpa_supplicant's documentation:
"psk: WPA preshared key; 256-bit pre-shared key
The key used in WPA-PSK mode can be entered either as 64 hex-digits, i.e., 32 bytes or as an ASCII passphrase (in which case, the real PSK will be generated using the passphrase and SSID). ASCII passphrase must be between 8 and 63 characters (inclusive)."
Whenever we see a 64 hex-digit passphrase, let's make sure it's passed unquoted. Since normal passwords need to be between 8 and 63 characters long, we also add some additional checks to be sure those conditions are fulfiled.
While at it, I changed most wifi test passwords as we were using exemplary passphrases that were shorter than 8 characters, which is not a good thing to demonstrate anyway.
This hopefully fixes: …

Fix quotation of WPA PSK 64 hex-digit keys for networkd 

---

tests/integration/base.py
tests/integration/ethernets.py

NetworkManager changed the "startup complete" behavior in v1.22, this is  why in some cases the test runs, even though the network is not yet fully up and running (i.e. only IPv6, not IPv4 & IPv6).
see: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/commit/1e5206414af83ede1e4e1ff6f525161b83519845
This is why we use libnm and pygobject to check for the n-m internal NM_ACTIVATION_STATE_FLAG_IP4_READY flag via d-bus, instead of just waiting for the `nm-online` binary ("startup complete" state).
In order to make the tests run, we **need the following dependencies** inside the Debian package (`debian/tests/control`), for the "ethernets" test:
+  libnm0,
+  python3-gi,
+  gir1.2-nm-1.0,

Adopt integration tests for NetworkManager v1.22 (focal)

---

Makefile

Currently the symbolic link of the `netplan-dev` package installs an invalid link to an absolute location of the build environment/machine.
We need to fix the _Makefile_, to install a relative symbolic link instead:
`libnetplan.so -> libnetplan.so.0.0`

Fix symbolic link of libnetplan.so installation in Makefile

---

src/networkd.c

Fix function _write_wpa_unit(..._ absence of derective "Require=" for systemd service Unit. 
It cause wpa_supplicant service to failed on boot.
Checklist for **aarch64** and **x64**

Fix missing Require= in service unit

---

doc/netplan.md
src/networkd.c
src/nm.c
src/parse.c
src/parse.h
tests/generator/test_common.py
tests/generator/test_errors.py

Allow to choose the configure method for creating the address for use with RFC4862 IPv6 Stateless Address Autoconfiguration. Possible values are: `eui64` or `stable-privacy`. If unset, the backend's default value stays in place.

Add IPv6 addr-gen-mode field for NM backend

---

doc/netplan.md
src/networkd.c
src/nm.c
src/parse.c
src/parse.h
src/util.c
src/util.h
src/validation.c
src/validation.h
tests/generator/test_errors.py
tests/generator/test_wifis.py

This PR implements the following WiFi fields, required by the "NetworkManager readwrite plugin" spec, for the `nm` and `networkd` backends. systemd-networkd does not support _seen-bssids_.
- band
- bssid
- channel
- seen-bssids

Implement WiFi flags for bssid/band/channel

---

doc/netplan.md
src/networkd.c
src/nm.c
src/parse.c
src/parse.h
tests/generator/test_wifis.py

This implements the `wakeonwlan` setting, which can contain any combination of the following flags:
- any
- diconnect
- magic_pkt
- gtk_rekey_failure
- eap_identity_req
- four_way_handshake
- rfkill_release
- tcp (NM only)
Or the exclusive ``default`` flag, to fall back to system defaults.

Implement WakeOnWLan for NM and networkd backends

---

doc/netplan.md
netplan/cli/sriov.py
src/parse.c
src/parse.h
tests/generator/test_ethernets.py
tests/test_sriov.py

This is a possible feature request to the just-landed SR-IOV support in netplan. This PR introduces an optional 'virtual-functions:' parameter that can be defined for physical functions to force the allocation of a given number of VFs, regardless of how many are actually used in the netplan config. There are of course safety checks to ensure that we can't request less VFs than actually needed in netplan.
This feature request came from the OpenStack team. We did consider such a thing originally, but then decided that it's better if we let netplan handle it. This PR adds this as an option (not recommended for everyday usage tho).

SR-IOV support for explicitly defining the VF count

---

doc/netplan.md
src/parse.c

Fix typo in documentation where "networks:" should be "network:".

Change "networks:" typo to "network:".

---

netplan/cli/commands/apply.py
netplan/cli/utils.py
src/networkd.c
tests/generator/test_wifis.py
tests/integration/base.py

Seems like the 'netplan apply' command was not properly adopted in https://github.com/CanonicalLtd/netplan/pull/109 when wired wpa_supplicant support was introduced.
Fixes: https://bugs.launchpad.net/ubuntu/+source/netplan.io/+bug/1874377

Fix LP#1874377: Not connect to WiFi after 'netplan apply'

---

doc/netplan.md
src/networkd.c
src/nm.c
src/parse.c
src/parse.h
tests/generator/test_errors.py
tests/generator/test_wifis.py

We got bit this week by not being able to connect to a "hidden" WiFi network with Netplan. A quick search brought up this top result, and we were able to work around the issue with the posted hack:
https://askubuntu.com/questions/1111494/netplan-not-connecting-to-hidden-ssid-server-18-04-1-lts
I'm a first-time contributor, but it didn't take me too long to get this working. The existing code is pleasantly clear and organized! I did notice some repeated code in the `handle_[foo]_bool` methods - I think this is now the third such method. Should some of this logic be moved into a `handle_generic_bool` function? I'm also not familiar with the other backends, so please let me know if there is work to be done to make this more broadly applicable.
The first two checklist items are pending, as I …

Add `hidden` to connect to non-broadcast SSIDs

---

netplan/cli/commands/apply.py
netplan/cli/utils.py
tests/integration/base.py

When running `netplan apply` systemd unit files might be created/deleted/changed on disk. We need to run `systemctl daemon-reload`, to make systemd aware of those new units and calculate the new unit/service dependencies. Otherwise it will throw warnings at us:
```
ubuntu@ubuntu:~$ sudo netplan apply
Warning: The unit file, source configuration file or drop-ins of netplan-wpa-wlan0.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of netplan-wpa-wlan0.service changed on disk. Run 'systemctl daemon-reload' to reload units.
```
Fixes: https://bugs.launchpad.net/ubuntu/+source/netplan.io/+bug/1874494

Call daemon-reload after we touched systemd unit files (LP: #1874494)

---

src/parse.c
tests/generator/test_bonds.py

The netplan parser might run multiple passes, if unknown interfaces/netdefs are detected during a prior pass. In that case it would fail to set a bond's primary slave, because it was set before (to the same interface).
Fixes: https://bugs.launchpad.net/ubuntu/+source/netplan.io/+bug/1817651

Don't fail if same primary slave was set before (LP: #1817651)

---

Makefile
doc/netplan.md
src/generate.c
src/networkd.c
src/openvswitch.c
src/openvswitch.h
src/parse.c
src/parse.h
src/util.c
tests/generator/base.py
tests/generator/test_ovs.py

This basically adds support for generating systemd unit files that would then later configure the OVS bits for devices that require it. The only schema piece supported right now is 'other-config' and 'external-ids', which were quite easy to do as they directly pass-through to OVS. Global setting not yet supported.
There is a basic OVS test to confirm that the parser and generator changes work.

[WIP] Initial first-try framework for OpenVSwitch schema

---

doc/netplan.md
src/nm.c
src/parse.c
tests/generator/test_ethernets.py
tests/generator/test_routing.py

For NetworkManager, implement some routing attributes and matching interfaces by glob pattern.
On problem is, that certain of these features require a recent enough NetworkManager. Otherwise, NetworkManager will ignore the setting or fail to load it. I don't think that general problem is solved (nor do I see it solved for networkd).

nm: support route attributes "from", "onlink", and "table" and "match.interface-name"

---

netplan/cli/commands/apply.py

b7f1d9b04212 refactored `process_link_changes` with helper methods to get
the interface driver name and MAC address. This new code introduced a
regression where it's possible for an interface in the up state to be
included in the changelist by its MAC address.
This patch restores the previous behaviour, skipping interfaces that
don't have driver_name set.
Fixes: https://bugs.launchpad.net/bugs/1875411

Fix process_link_changes handling 'up' interfaces

---

doc/netplan.md
netplan/cli/commands/apply.py
src/openvswitch.c
src/parse.c
src/parse.h
tests/generator/base.py
tests/generator/test_ovs.py
tests/integration/ovs.py

This adds support for OpenVSwitch bonds, with the additional `parameters->mode` (`balance-tcp` & `balance-slb`) and `openvswitch->lacp` fields.
It implements `netplan apply` for OVS devices, defines systemd unit-file dependecies for OVS devices and adds a new, basic integration test for OVS.

OpenVSwitch Bonds

---

doc/netplan.md
tests/validate_docs.sh

Documenting the first version when a new feature (config key) was introduced down to `v0.96`. No new keys were introduced in 0.96.

Doc: Mark versions of new config keys

---

tests/integration/ethernets.py
tests/integration/routing.py

This should actually fail if used with NetworkManager < 1.14, e.g. on Ubuntu Bionic.

Add itegration tests for interface globbing and NM routing

---

netplan/cli/commands/apply.py
netplan/cli/utils.py
tests/integration/ethernets.py
tests/test_utils.py

On `arm64` we had a test failure in `tests/integration/ethernets.py` -> `test_manual_addresses`, which was caused by the fact that `netplan apply` was disconnecting ALL available network interfaces via `nmcli`, in order to reload the new netplan config. This way the IP of the 2nd test DHCP server (dnsmasq on `veth43`) was lost and did not provide correct responses for the rest of the test.
It is not necessary to take all interfaces down, only the ones which are (or were) configured via netplan. This was fixed in the `netplan apply` command.
**Note:** This should make its way into the Groovy package as a distro-patch, to avoid future autopkgtest failures.

Fix autopkgtest on arm64 with NM 1.24

---

doc/netplan.md
src/openvswitch.c
src/parse.c
src/parse.h
src/validation.c
src/validation.h
tests/generator/test_ovs.py
tests/integration/ovs.py

Adds support for the OpenVSwitch Bridge `controller.addresses` config key to specify OpenFlow controller targets and `controller.connection-mode` config key, to define if the controller shall be used in a `in-band` or `out-of-band` configuration.
Additionally, it adds support for the following global `openvswitch.ssl` configs, which need to be used if a `ssl:` or `pssl:` OpenFlow controller target is to be used.
* ca-cert
* certificate
* private-key
It adds a new integration test in `tests/integration/ovs.py`, which we need to make sure to integrate into the debian package (via `debian/tests/control`), to have it run during `autopkgtest`.

OVS: Add support for bridge controller configuration

---

src/networkd.c
src/openvswitch.c
tests/generator/base.py
tests/generator/test_ovs.py
tests/integration/ovs.py

* Throw error, if OVS backend is applied to an unsupported interface type.
* Check for existence of all OVS systemd unit files in unit-tests
* Add (preliminary) VLAN-Bridge integration test for OVS

OVS: Improve unit- & integration tests, throw error about unsupported OVS interfaces

---

doc/netplan.md
src/networkd.c
src/openvswitch.c
tests/generator/test_ovs.py
tests/integration/base.py
tests/integration/ovs.py

The spec defined fake VLAN bridge structures, but wasn't very clear about it being in scope. Let's add those now.

Base support for OVS fake VLAN bridges.

---

examples/static.yaml

Suddenly jumped from 2 spaces to 4 spaces for no apparent reason.

Inconsistent indentation

---

src/parse.c
tests/generator/test_ovs.py

It was not mentioned explicitly by the spec, but there was actually not much about VLAN support at all. After some discussions with James, it seems like we would want to have the same logic for VLANs as we have for bridges and bonds: if a VLAN is defined for an OVS interface, switch the backend to OVS as well.

Allow for fake VLAN bridges to be implicit for OVS

---

netplan/cli/commands/apply.py
netplan/cli/commands/try_command.py
netplan/cli/ovs.py
src/openvswitch.c
src/util.h
src/validation.c
tests/generator/base.py
tests/generator/test_args.py
tests/generator/test_ovs.py
tests/integration/base.py
tests/integration/ovs.py

This provides general cleanup of the OVS codebase, such as test and comment improvements.
It also makes sure that left-over OVS interfaces (tagged `netplan=true`) are cleaned up during `netplan apply`, by executing `del-br/del-port` on those interfaces. All `ExecStop=` commands and `RemainAfterExit=true` have been removed and all cleanup is now done via the `netplan-ovs-cleanup.service` unit, which runs prior to the other `netplan-ovs-*.service` units.
I'm adding a new parameter `netplan apply --ovs-only` (called via `netplan-ovs-cleanup.service` as well), which will just clean up all `netplan=true` taged OVS interfaces (Bridges/Ports/Bonds), if they are not defined in the current YAML config.
I reduced the usage of `systemd_escape()` even more, to have it only escape interface names, if …

Cleanup OVS code and (old) OVS interfaces after 'netplan apply'

---

src/parse.c
src/parse.h
src/util.c
src/util.h

GCC-10 defaults to `-fno-common`. Netplan fails to link with GCC 10 due to a repeated non-extern variable declaration in a header used across multiple source files.
https://bugs.debian.org/957603
https://gcc.gnu.org/gcc-10/porting_to.html

Fix GCC-10 -fno-common linker errors (LP: #1875412)

---

netplan/cli/commands/apply.py
netplan/cli/ovs.py
src/openvswitch.c
tests/generator/test_ovs.py
tests/integration/ovs.py

* Fix `only_ovs_cleanup` argument, to make it execute the correct code.
* Execute the `oneshot` OVS systemd units synchronously, to avoid race conditions during `systemctl start ...`.
* Set OVS patch ports atomically, to avoid logging errors.
* Clean up OVS fake VLAN bridges from the `Interface` table via `del-br`

Fix OVS cleanup and systemd race conditions

---

doc/netplan.md
src/networkd.c
src/nm.c
src/parse.c
src/parse.h
tests/generator/base.py
tests/generator/test_common.py
tests/generator/test_errors.py

This patch introduces a way to set options for the [Address] section in the networkd backend. It changes the addresses YAML key to a sequence of scalars and mappings, keeping backward compatibility with the previous address notation.
We can extend the current address notation either flattened or expanded, e.g. below:
```
addresses: [192.168.14.2/24, "2001:1::1/64": {lifetime: 0}]
```
```
addresses:
- 192.168.14.2/24:
lifetime: 0
label: test-label
- 2001:FFfe::1/64''')
```
Due to the nature of the networkd backend, addresses which have these options set need to be placed in their separate [Address] section in the resulting `.network` file.
Two keys are supported for now: `lifetime` and `label`, which correspond to their networkd counterparts `PreferredLifetime` and `Label`. I've tried to …

Introduce support for networkd address options

---

netplan/cli/commands/apply.py
netplan/cli/utils.py
tests/test_utils.py

There might be scenarios, where leftover IP addresses are assigned to a
given interface. This confuses NetworkManager and makes it create a new,
non netplan-* connection profile, using this leftover IP.
Flush the IP addresses of all NM managed interfaces, to avoid this
situation.
Fixes LP: #1870561
This PR passes all unit- and integration-test and the manual testing.

Flush IPs of NM managed interfaces (LP: #1870561)

---

netplan/cli/ovs.py
netplan/configmanager.py
src/openvswitch.c
src/parse.c
src/util.h
tests/generator/base.py
tests/generator/test_ovs.py
tests/integration/ovs.py
tests/test_configmanager.py
tests/test_ovs.py

This PR implements the "Common tags for all device types" section of the spec.
Whenever any OVS setting is applied inside the ovsdb, this code adds another setting for the corresponding interface inside the `external-ids` table, e.g.:
* `ovs-vsctl set-ssl client-key client-cert ca-cert`
* `ovs-vsctl set open_vswitch . external-ids:netplan/global/set-ssl=client-key,client-cert,ca-cert`
or:
* `ovs-vsctl set Bridge ovs0 other-config:some-key=42`
* `ovs-vsctl set Bridge ovs0 external-ids:netplan/other-config/some-key=42`
or:
* `ovs-vsctl set Port ovs1 lacp=off`
* `ovs-vsctl set Port ovs1 external-ids:netplan/lacp=off`
The netplan settings tag (`netplan/<column>[/<key>]=<value>`) marks the settings (`column[:key]=value`) inside ovsdb state, so that it can be cleaned up via `netplan apply …

Tagging & cleanup of individual OVS settings

---

Makefile
doc/netplan.md
netplan/cli/commands/apply.py
netplan/cli/commands/try_command.py
netplan/cli/ovs.py
netplan/configmanager.py
src/generate.c
src/networkd.c
src/networkd.h
src/openvswitch.c
src/openvswitch.h
src/parse.c
src/parse.h
src/util.c
src/util.h
src/validation.c
src/validation.h
tests/generator/base.py
tests/generator/test_args.py
tests/generator/test_ovs.py
tests/integration/base.py
tests/integration/ovs.py
tests/test_configmanager.py
tests/test_ovs.py
tests/validate_docs.sh

Finally merge the work-in-progress OpenVSwitch support branch to master. Currently the branch should be feature-complete as per the initial specification, meaning we support:
* OVS bridges
* OVS bonds
* OVS patch ports
* Custom settings like SSL config, other-config, external-ids etc.
* Fake VLAN bridges
This version also attempts to do smart cleanup of the configuration, removing no-longer relevant configuration on every `netplan apply` or system reboot.

Openvswitch support (LP: #1728134)

---

doc/netplan.md
src/networkd.c
src/nm.c
src/parse.c
src/parse.h
src/validation.c
tests/generator/test_common.py
tests/generator/test_errors.py
tests/integration/ethernets.py

This allows to statically configure the IPv6 host ID (low 64 bits) when auto-generated IPv6 addressing is used (i.e. DHCPv6 stateless, SLAAC).
It introduces one new YAML key in the schema: `ipv6-address-token-id`.
Fixes LP: #1737976

Implement ipv6-address-token-id key (LP: #1737976)

---

doc/netplan-generate.md
src/generate.c
tests/integration/base.py
tests/integration/cloud-init.py

If system is initializing (basic.target not reached yet), and `netplan
generate` is called ensure that any netplan generated service units
are added to the initial boot transaction.
This should resolve cloud-init first-time booting with
systemd-networkd disabled, or with requirement to add wlan/wifi units.
I've tested this by sideloading this new code branch to lxd container.
Disabling systemd-networkd `systemctl disable systemd-networkd`
Removing `rm -rf /etc/netplan/50-cloud-init.yaml /var/log/cloud-init-output.log /var/log/cloud-init.log`
Executing `cloud-init clean`
And rebooting.
On reboot, I observed, that despite not being enabled systemd-networkd & netplan-ovs-cleanup did start or attempted to start, at the right time during initial boot, and correctly ordered before reaching …

generate: implement just-in-time behaviour for generate

---

netplan/cli/commands/info.py

Remove version information from the `info` flag description. Version information has been removed [in this commit](https://github.com/CanonicalLtd/netplan/commit/9ea105bef2cea28916213aad93a37ea85d89fdbc), but the message hasn't been updated.

Remove version information from the description of the info flag

---

src/openvswitch.c
tests/generator/base.py

Netplan's Open vSwitch helper units are started too late, which makes `systemd-networkd-wait-online.service` fail the first time it is started. This leads to `cloud-init init` running in an invalid state, thus failing, which in turn makes the system (deployed via MAAS) end up with broken networking.
The helper units only depend on OVSDB, which is started in `network-pre.target`, thus we can make them depend on `ovsdb-server.service` instead of `openvswitch-switch.service`, to avoid failures in `wait-online`.

Fix MAAS/OVS first boot for single NIC/PXE systems

---

src/networkd.c
tests/generator/base.py
tests/generator/test_vlans.py

Fix systemd-networkd misconfiguration; when matching on macaddr, if other interfaces in the system might have the same mac (e.g. bridge, vlan, etc), the match filtering must also filter which interface to match, e.g., besides the MACAddress= match it also needs (for example) one or more of:
* Type=!vlan
* Type=!bridge
PS: also cleaning up the `test_vlans.py` file a bit, while working on it.

Do not try to match/rename duplicated MAC of vlan (LP: #1888726)

---

doc/netplan.md
src/networkd.c
src/nm.c
src/parse.c
src/parse.h
tests/generator/test_errors.py
tests/generator/test_routing.py
tests/integration/routing.py

This patch introduces a way to set MTU for specific routes. It adds an 'mtu'
field to the `NetplanIPRoute` struct, and makes use of already existing route
handling code to add the MTU-related fields for networkd and NM backends.

Add per-route MTU option (LP: #1860201)

---

netplan/cli/commands/try_command.py
netplan/terminal.py
src/dbus.c
tests/dbus/test_dbus.py
tests/test_terminal.py

Implement the `Try(uint32 timeoutInSeconds)` and `Cancel()` command inside `netplan-dbus` and adopt the `Apply()` command according to spec. "Try(...)" calls `netplan try`, keeping `stdin` open. The "Apply()" command uses the `SIGUSR1` signal, to send a confirmation to the `netplan try` process to confirm/commit the settings. The "Cancel()" command uses the `SIGINT` signal, to send a rejection to the `netplan try` child process.
The child process is being monitored, using events on the sd-event mainloop.
Codecov reports a reduced coverage, but that is only because the code in `terminal.py` cannot be tested from a script, as it uses the `isatty()` condition. And that part is excluded/skipped from our test-suite if run inside a script. If `make check-coverage` is executed locally, it …

Implement DBus try-commit handling

---

Makefile
dbus/io.netplan.Netplan.conf
netplan/cli/commands/set.py
src/dbus.c
src/generate.c
src/util.c
src/util.h
tests/dbus/test_dbus.py
tests/test_cli_get_set.py

This implements the `io.netplan.Netplan /io/netplan/Netplan io.netplan.Netplan Config` method, which creates new `/io/netplan/Netplan/config/<ID>` objects, providing the following methods:
* `io.netplan.Netplan.Config Get`
* `io.netplan.Netplan.Config Set`
* `io.netplan.Netplan.Config Try`
* `io.netplan.Netplan.Config Apply`
* `io.netplan.Netplan.Config Cancel`
And also the `io.netplan.Netplan.Config Changed` signal.
Each new config object will copy the current global netplan state (from `/etc/netplan`) to `/tmp/netplan-config-<ID>` then Get/Set can be called on that temp directory. On Apply/Try it will backup the current global config to `/tmp/netplan-config-BACKUP` and copy over the current config state to `/etc/netplan`. On revert the data from `/tmp/netplan-config-BACKUP` will be …

DBus Config Management (try-improvement)

---

Makefile
doc/manpage-footer.md
doc/netplan-dbus.md
doc/netplan-get.md
doc/netplan-set.md
doc/netplan-try.md
examples/dbus_config_scenario.txt
src/dbus.c

Add man pages for `netplan get/set` CLI and `Config/Try/Cancel/Apply/Get/Set` DBus methods.
This PR also adds a `dbus-config` feature flag, to indicate the availability of the DBus configuration management.

Documentation for get/set CLI and DBus Config/Try/Cancel/Apply/Get/Set

---

doc/netplan.md
netplan/cli/commands/apply.py
netplan/cli/utils.py
netplan/configmanager.py
tests/integration/ethernets.py
tests/test_utils.py

Renaming of network interfaces was not working when running `netplan apply` and interfaces would only be renamed after a reboot via udev. There is some udev-rename logic inside `cli/commands/apply.py`, which doesn't seem to be working, though.
This seems to be related to systemd-udevd's `NamePolicy=keep` default, which is set explicitly as of systemd v240 [0][1] and prevents renaming of interfaces via udev, if the name was set once (i.e. during boot). Even before v240 this has be the (implicit) default, so I'm not sure if this rename logic has ever worked...
I reworked/refactored the renaming of interfaces in `apply.py` to make use of iproute2 `ip link set eth_OLD set name eth_NEW` command instead and also added an integration test.
In order to rename interfaces via iproute2, they need to …

Fix rename of matched interfaces at runtime (LP: #1904662)

---

Makefile
src/dbus.c
src/networkd.c
src/parse.c

These fixes make sure we can compile and run tests using `CC=clang`

Clang fixes

---

src/networkd.c
tests/generator/test_bridges.py
tests/generator/test_ethernets.py
tests/generator/test_vlans.py
tests/integration/ethernets.py

Starting with systemd v247 the [.link](https://www.freedesktop.org/software/systemd/man/systemd.link.html#MACAddress=1) file section to change the MAC address does not seem to have an effect anymore:
```
[Link]
MACAddress=00:11:22:33:44:55
```
Changing/clearing `MACAddressPolicy=` did not help to make the .link file set the MAC address.
Whereas the same section applied to a [.network](https://www.freedesktop.org/software/systemd/man/systemd.network.html#MACAddress=1) file seems to fix the situation:
```
[Link]
MACAddress=00:11:22:33:44:55
```
Documentation indicates that those do the same thing, so I'm applying both now. It passes all integration tests this way, for old and new systemd.

Fix changing of macaddress with systemd v247

---

src/parse.c
tests/generator/test_modems.py

The `COMMON_BACKEND_HANDLERS` have been forgotten for `modem` connections apparently. Add them to allow the definition of the special `networkmanager:` mapping, used for NetworkManager integration. E.g. this `networkmanager.uuid` setting:
```
network:
version: 2
modems:
mycon:
auto-config: true
networkmanager:
uuid: b22d8f0f-3f34-46bd-ac28-801fa87f1eb6
```
We do not (yet) use that information (like uuid) in the current implementation. But reading YAML via NetworkManager will be broken if the `networkmanager:` mapping is not accepted.

Fix 'networkmanager:' backend options for modem connections

---

doc/netplan.md

Fixes [LP: #1909114](https://bugs.launchpad.net/netplan/+bug/1909114)

doc: Add a caveat to wake on LAN which is systemd.link related (LP: #1909114)

---

src/nm.c
tests/generator/test_bridges.py
tests/generator/test_common.py
tests/generator/test_ethernets.py
tests/generator/test_tunnels.py
tests/generator/test_vlans.py
tests/generator/test_wifis.py

This is the 3rd in a series of pull requests to enable the implementation of a YAML/netplan backend for NetworkManager.
In this PR netplan's current keyfile generation code (in `nm.c`) is refactored to make use of GLib's keyfile writer, instead of using a custom, home grown approach. This way the keyfile settings can easily be read, written and overwritten (e.g. by the keyfile passthrough/fallback settings in #183) and it should be more robust overall.
While on it: Clean up the usage of keyfile alias for `ethernet`, `wifi` and `wifi-security`, which NetworkManager writes by default since a long time, see: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/commit/c36200a225aefb2a3919618e75682646899b82c0

NM: refactor keyfile generator, by using GLib's keyfile writer instead of custom writer

---

netplan/cli/utils.py
tests/test_utils.py

In some cases the `netifaces.ifaddresses()` method returns an empty dict. Accessing this dict throws a `KeyError`, because there is no `netifaces.AF_LINK (= 17)` link layer address data.
```
File "/usr/share/netplan/netplan/cli/utils.py", line 169, in get_interface_macaddress
link = netifaces.ifaddresses(interface)[netifaces.AF_LINK][0]
KeyError: 17
```

cli:utils: handle emtpy netifaces.ifaddresess call (LP: #1913062)

---

src/generate.c
src/nm-keyfile.c
src/nm-keyfile.h
src/nm.c
src/parse.c
src/parse.h
src/serialize.c
src/serialize.h
src/util.c
src/validation.c
tests/cli.py
tests/generator/test_args.py
tests/generator/test_auth.py
tests/generator/test_modems.py
tests/generator/test_ovs.py
tests/generator/test_passthrough.py
tests/generator/test_wifis.py
tests/test_nm_backend.py

This PR is 6th in a series of pull requests to prepare for the NetworkManager YAML backend. It builds upon #183 and contains a few improvements and fixes, enabling the NetworkManager test-suite (i.e. `make check`) to fully pass, especially the tests in the patched keyfile plugin (`src/settings/plugins/keyfile/tests/test-keyfile-settings`).
It implements the following functionality:
* Adding some basic support for the `modems` YAML schema, to allow matching of (physical) modem interfaces and enable the detection of GSM vs CDMA connections, which are distinct in NM while using the same definition in Netplan.
* Switching the `passthrough` key-value pairs to a DataList (instead of HashTable), to keep order of the keyfile elements, which is relevant in some cases (e.g. for `tc.qdiscs`)
* Avoid …

Improvements for the NetworkManager YAML backend integration

---

doc/netplan.md
src/networkd.c
src/nm.c
src/parse.c
src/parse.h
tests/generator/test_errors.py
tests/generator/test_routing.py
tests/integration/routing.py

Add possibility to set initcwnd/initrwnd options on routes.

Added per route initcwnd/initrwnd option

---

doc/netplan.md
src/networkd.c
src/nm.c
src/parse.c
src/parse.h
src/validation.c
tests/generator/test_tunnels.py
tests/integration/tunnels.py

Some protocols set the TTL field of the packet to 1; when passing through the tunnel, the packet is discarded. To solve the problem, the tunnel has the TTL option, but it was not in netplan.
According to https://bugs.launchpad.net/netplan/+bug/1846783 this is required for IPIP/SIT/GRE tunnels.

Added TTL option for tunnels (LP: #1846783)

---

tests/integration/base.py
tests/integration/wifi.py

* Encapsulate wifi tests into own test class (requiring `modprobe`, i.e. isolation-machine level).
* Make sure the management always stays up an connected (incl. DNS), independently of netplan

Improve integration tests

---

src/parse.c
tests/generator/test_common.py

…(LP: #1915837)
https://bugs.launchpad.net/netplan/+bug/1915837
Using arp-ip-targets as below is generating 10-netplan-bond0.netdev file which contains ARPIPTargets property with duplicated values;
> arp-ip-targets:
>         - 10.10.10.10
>         - 20.20.20.20
> ARPIPTargets=10.10.10.10 20.20.20.20 10.10.10.10 20.20.20.20
Duplicate values in ARPIPTargets prevents systemd-networkd to process the netdev file due to a validation error in Ubuntu 18.04LTS.

Prevent duplicate ARPIPTargets in NetDev files (LP: #1915837)

---

doc/netplan-set.md
netplan/cli/commands/get.py
netplan/cli/commands/set.py
netplan/cli/utils.py
src/dbus.c
src/util.c
src/util.h
tests/dbus/test_dbus.py
tests/test_cli_get_set.py
tests/test_utils.py

This PR builds upon some functionality from #193, so that one should be merged first. It extends the existing CLI functionality of `netplan set` to auto-detect the filename of the corresponding YAML config which contains the original definition of this netdef. If, for example, there is a config file `/etc/netplan/00-my-manual-config.yaml` containing a definition for `eth0` and we're calling `netplan set network.ethernets.eth0.dhcp4=false`, that setting will be overridden in **00-my-manual-config.yaml** instead of masking it via **70-netplan-set.yaml**.
If the **set** command contains multiple netdefs (e.g. `netplan set network="{ethernets:{eth0:{dhcp4: true}}, bridges:{br0:{dhcp6: true}}}"`), each will be checked individually and written to its corresponding file. If there is no prior …

cli:set: write to existing YAML file, if available

---

netplan/cli/commands/apply.py
netplan/cli/utils.py
tests/test_utils.py

Replace the calls of `systemctl stop/start systemd-networkd.service` with `networkctl reload && networkctl reconfigure ...` during the execution of `netplan apply`. The devices to be reconfigured are currently all interfaces managed by systemd-networkd, as read from `networkctl`. This makes the whole restart/apply process quicker and avoids network interruptions for netplan's networkd backend.
The reload & reconfigure commands are available as of **systemd v244**.
In addition to the Apply-CLI changes, corresponding methods in `utils.py` are updated/refactored and the unit-test coverage is being improved.

networkd: restart/reconfigure

---

netplan/cli/ovs.py
tests/integration/ovs.py
tests/test_ovs.py

Bug fix for https://bugs.launchpad.net/netplan/+bug/1918197 and https://bugs.launchpad.net/netplan/+bug/1913906
Fixes the parse error for dict values that include ":"
`make check-coverage` errors out with less than 100% but so does the tip of master.
No new or changed keys.

Fix parsing of OVS values with colons (LP: #1913906)

---

netplan/cli/commands/set.py

Using os.replace() leads to "Invalid cross-device link" errors on Core20 setups, due to having different mounts.
Use shutil.copy() & os.remove() instead.

cli:set: Fix netplan-set on Core20

---

doc/netplan-dbus.md
netplan/cli/commands/apply.py
netplan/cli/commands/generate.py
src/dbus.c
tests/dbus/test_dbus.py

Proxy the 'netplan generate' CLI via DBus, if called from within a snap,
to work around the strict AppArmor confinement.
see: https://github.com/snapcore/snapd/pull/10212

dbus:cli: implement io.netplan.Netplan.Generate()

---

src/netplan.h

NETPLAN_DEF_TYPE_VIRTUAL and NETPLAN_DEF_TYPE_BRIDGE point
to same value in enum, however here they are assigned individually
which results in overriding the initialization of the objects
Fixes
src/netplan.h:85:33: error: initializer overrides prior initialization of this subobject [-Werror,-Winitializer-overrides]
[NETPLAN_DEF_TYPE_BRIDGE] = "bridges",
^~~~~~~~~
Signed-off-by: Khem Raj <raj.khem@gmail.com>

Handle enum element override

---

src/generate.c
src/openvswitch.c
src/util.c

In modern systems `/sbin` is a symlink to `/usr/sbin`, we should not be calling `/sbin/netplan` directly (neither `/usr/sbin/netplan`), but make use of the `SBINDIR` build time variable.
Furthermore, the `/sbin/udevadm -> /bin/udevadm` is not shipped by systemd-udev anymore since Focal, so we should be calling the real binary at `/bin/udevadm` instead.

Improve subprocess calls to binaries in /sbin + udevadm

---

src/nm.c
tests/generator/test_ethernets.py
tests/generator/test_vlans.py

* nm: fix ignoring of multiple match conditions (like `interface-name:` AND `mac:`, instead of defaulting to MAC if available)
* Some interfaces (e.g. bond members) might change their MAC and be picked up ny NM, interfering the tests, cf. `test_bond_mac/Networkd`

Fix NM unmanaged-devices (changes behavior)

---

doc/netplan.md
src/networkd.c
tests/generator/test_common.py

When the networkd backend is used, whenever an interface defines `activation-mode` it also needs to be implicitly marked as `optional`. Both of the available `activation-mode` states end up with the interface not being brought up by networkd on boot, and this can cause systemd to wait indefinitely for the interface to go online during wait-online. Currently systemd doesn't make this `NeededForOnline=no` assumption for us, so we need to do it ourselves.
I tried re-using the existing code for marking as optional not to duplicate too much code, so it's basically just moving stuff around.

Implicitly consider devices with activation-mode set as optional

---

tests/integration/base.py
tests/integration/bonds.py
tests/integration/bridges.py
tests/integration/ethernets.py
tests/integration/ovs.py
tests/integration/regressions.py
tests/integration/routing.py
tests/integration/scenarios.py
tests/integration/tunnels.py
tests/integration/vlans.py
tests/integration/wifi.py

This is a big refactoring of the integration test suite, which should make it much faster and more stable in different testing environments (e.g. armhf LXD containers).
The main change is in `tests/integration/base.py` and changes the waiting logic to decide when an given interface is readily configured. Previously, we were relying on `/lib/systemd/systemd-networkd-wait-online` to tell us magically when the networking is fully configured. This does not properly work for interfaces controlled by NetworkManager and is only watching the "general" networking state (i.e. whenever the first interface is up and running).
Waiting only on an arbitrary "first" network interface to be ready leads to races as we use asserts on many individual interfaces, which might not be ready at that time. So with …

Improve integration tests interface-ready waiting logic (LP: #1922126)

---

src/parse.c
src/validation.c
src/validation.h
tests/generator/test_errors.py

It doesn't make sense for the user to have multiple global gateways. This patch introduces a consistency check at the end of the parsing stage, and only emits a warning in order not to break current configurations.
Addresses LP #1901836

parser: warn user on multiple global gateway (LP: #1901836) (FR-728)

---

src/parse.c

Parsing a yaml route looking like this:
```yaml
routes:
- to: 162.168.0.0/16
- to: invalid value
```
would result in having a dangling pointer in cur_route->to, as its
content would have been freed when starting to parse the invalid value,
without the pointer itself having been cleared. By deferring the free() to
right before the pointer update, we ensure that (barring interrupts or
multithreading, neither of which are supported AFAIK) the pointer remain
valid.
Note that to be thread-safe, we'd need to do an atomic swap and only
then free the variable, but that's out of scope ATM.

parse: routes: avoid creating dangling pointers on error

---

doc/example-config
doc/netplan.md
examples/bonding_router.yaml
examples/ipv6_tunnel.yaml
examples/source_routing.yaml
examples/static.yaml
examples/static_multiaddress.yaml
examples/vlan.yaml
examples/wireguard.yaml
examples/wireless.yaml
src/networkd.c
src/nm.c
src/parse.c
src/util.c
src/util.h
src/validation.c
src/validation.h
tests/generator/test_common.py
tests/generator/test_errors.py
tests/generator/test_routing.py
tests/integration/routing.py

This patchset deprecates the `gateway4/6` fields, advising the user to use a proper route instead. The rationale is that it groups all routing matters in the same place, making things more consistent. Along with this deprecation comes the support for the "default" keyword in the route `to` field, and an expansion of the gateway validation step to encompass all default routes.
```yaml
network:
ethernets:
en1:
addresses:
- 1.2.3.4/8
- fc00:123:4567:89ab:cdef::1234/64
routes:
- to: default
via: 1.1.1.1
- to: default
via: "fc00:123:4567:89cb:cdef::1"
```
Addresses LP: #1756590

Gateway fields deprecation and default routing support (FR-728) (LP: #1756590)

---

netplan/cli/commands/apply.py
tests/test_cli_units.py

The code path when a config has `set-name` as well as `bridges` doesn't seem to work at present, failure below. This change seems to fix it. 
Config:
```yaml
network:
version: 2
ethernets:
devnet:
renderer: networkd
match:
name: enx00aa11223344
enx00bb11223344:
addresses: [ 10.20.0.1/24 ]
renderer: networkd
wlan:
match:
macaddress: 00:99:11:22:33:44
set-name: "wlan0"
bridges:
renderer: networkd
br0:
addresses: [ "10.9.0.1/16" ]
interfaces: [ "devnet" ]
```
```
netplan try
File "/usr/share/netplan/netplan/cli/commands/try_command.py", line 84, in command_try
NetplanApply().command_apply(run_generate=True, sync=True, exit_on_error=False)
File "/usr/share/netplan/netplan/cli/commands/apply.py", line 191, in command_apply
changes = …
```

cli: Fix failure with "set-name" and "bridges"

---

.editorconfig

The `Convenientions` section in `CONTRIBUTING` emphasizes an
indentation of 4 spaces which is not always the default in the
developer's environment. The EditorConfig project aims to maintain
consistent styles across various IDEs and editors. Some editors
natively support EditorConfig [1] and for some editors a plugin to
support EditorConfig can be downloaded [2].
[1] https://editorconfig.org/#pre-installed
[2] https://editorconfig.org/#download
Signed-off-by: Nicolas Bock <nicolas.bock@canonical.com>

Add `.editorconfig` for convenience

---

doc/netplan.md
src/parse.c

This gives a better hint on how to add a link local route.  Ie., if the user tries to add a local route (without a gateway (`via`)), they will get an error message that a global route needs `via`, and hopefully understand they should use `scope: local`.  Also, the docs spell this out.

clarify requirements for a link local route

---

Makefile
src/netdef.c
src/netplan.c
src/networkd.c
src/parse-nm.c
src/parse.c
src/parse.h

This PR is mostly about cleaning up the NetplanNetDefinition objects, and when to do it. There are a couple of precursor commits that either made the transition easier or fixed some bugs that were uncovered when actually trying to clean up things ;).
There are no API or ABI change, although there's one observable change with the `dhcp_identifier` which now defaults to `NULL` instead of an owned string `"duid"`. The rationales are in the commit that makes the change.
As usual, each commit log contains some context information related to each change, and the commits are split up with the explicit intent of making it easier to review, one commit at a time.

NetDefinition: ownership and cleanup (FR-786)

---

tests/generator/base.py

The YAML normalizer has some special cases for some given keys. However,
the code block where those are dealt with used `elif` everywhere, which
meant that if a single dict had multiple keys needing to be dealt with,
only the first one would be fixed, and the rest would continue on, still
broken.
This bug is latent in the current codebase, but it showed up in a
patchset I'm working on, where by the game of butterfly effects the
rendered configuration would insist on having proper renderer for each
netdef. This key needs normalizing, but in the test cases where the
netdefs have other problematic properties, for instance the GSM config
in `test_cdma_config`, those pesky renderer lines would still show up
and screw up the test.

tests: normalize multiple keys on a single dict

---

doc/netplan-apply.md
netplan/cli/commands/apply.py
netplan/cli/commands/try_command.py
netplan/configmanager.py
src/dbus.c
tests/dbus/test_dbus.py
tests/integration/base.py
tests/integration/scenarios.py
tests/test_cli_units.py
tests/test_configmanager.py

Allow to pass an optional `--state` parameter to `netplan try/apply` describing a directory that contains a netplan configuration tree/state (i.e. `/{etc,run,lib}/netplan/*.yaml`).
Netplan will make use of this "old state" to calculate the delta of dropped interface definitions, like bridges/bonds/vlans/tunnels that have been configured before but are not part of the current YAML configuration anymore. It will then try to delete those virtual interfaces (via `ip link del dev IFACE`) if they still exist.
The same functionality is used to roll back a `netplan try` command that failed or was rejected.
Generally, the state needs to be provided manually. The DBus API (using io.netplan.Netplan.Config.Try/Apply) is an exception, as the previous state can be backed up automatically in this case.

Implement YAML state tracking and use it in the DBus API and netplan-try (LP: #1943120) (FR-1745)

---

doc/netplan.md
examples/offload.yaml
src/netplan.c
src/networkd.c
src/parse.c
src/parse.h
tests/generator/test_ethernets.py

This change adds `systemd` support for additional configuration options for interfaces.
* ReceiveChecksumOffload
* TransmitChecksumOffload
Closes: https://bugs.launchpad.net/netplan/+bug/1771740
Signed-off-by: Nicolas Bock <nicolas.bock@canonical.com>

Add support for additional `Link` options (LP: #1771740)

---

netplan/cli/commands/set.py
netplan/cli/utils.py
src/names.c
src/names.h
src/util.c
tests/test_cli_get_set.py
tests/test_utils.py

Previously, trying to unset a whole devtype subtree, such as `netplan set network.ethernets=null` would fail. This PR fixes it by detecting this special case and manually deleting each netdef assigned to the subtype.
This approach is far from being performant, but it has the merit of working without needing too much new code.

netplan: set: make it possible to unset a whole devtype subtree (LP: #1942930) (FR-1685)

---

src/parse.c

This PR rework some error handling paths, to achieve two results:
* Avoid as much as possible putting data in a netdef before it has been validated. This makes recoverable error handling much easier, and also facilitates debugging: reducing side effects means enhanced local reasoning, resulting in less headaches ;)
* Be consistent regarding `GError**` acceptable values. Most of the code assumes that actual error signalling is done via the value returned on the stack, either via `FALSE` or `NULL`, but a couple of places would use the GError mechanisms instead. This meant that providing `GError** error = NULL` would mostly work, but for those places where the code would glance over some failures as it wouldn't be able to detect them.

parser: fix some error handling code

---

src/types.c

This change adds code to reset the offload options.

Reset offload options

---

netplan/cli/commands/apply.py
tests/integration/regressions.py

The `self.state` attribute needs to be available even if NetplanApply() is not executed via the command line (and thus the `run()` method is not executed).
Fixes a regression in #231

cli:apply: initialize self.state (LP: #1949104)

---

include/netplan.h
include/parse-nm.h
include/parse.h
netplan/cli/utils.py
src/abi_compat.c
src/error.c
src/error.h
src/generate.c
src/netplan.c
src/networkd.c
src/parse-globals.h
src/parse-nm.c
src/parse.c
src/types.c
src/types.h
src/util-internal.h
src/util.c
src/validation.c
src/validation.h
src/yaml-helpers.h
tests/generator/test_dhcp_overrides.py
tests/parser/base.py
tests/test_libnetplan.py

Instead of directly writing into the final network state, use a separate
global parser object to store any intermediate data needed during
parsing. This allows us to ensure that the client can only see valid
configurations, as the parser is opaque to the client, who then must
call our functions to import *and validate* the data into the final
network state.
Since the public API doesn't allow us to pass around some context, we
still store a static object to use in those APIs, but all the internal
functions shouldn't touch any external data.
This PR depends on #229 and #227 and is only a prequel to the proper YAML
parser unification work, which will start with the removal of the current parsing
API, replaced by one based on explicitly allocated states, in conjunction with
the #232 work. To …

lib: use an explicit parser context

---

src/nm.c
tests/generator/base.py
tests/generator/test_common.py
tests/generator/test_dhcp_overrides.py
tests/generator/test_routing.py
tests/generator/test_tunnels.py
tests/generator/test_vlans.py
tests/parser/base.py
tests/parser/test_keyfile.py

…and ipv6-privacy is false
Fix for https://bugs.launchpad.net/bugs/1948027

Disable temporary address generation when renderer is NetworkManager (LP: #1948027) – change in behavior

---

src/abi_compat.c
src/parse-nm.c
tests/parser/base.py
tests/parser/test_keyfile.py

netplan's keyfile parser can handle certain device types and settings from NM's keyfile format. But we should try to avoid writing out partial YAML where some (essential) fields are missing, as they cannot (yet) be properly parsed.
We need to check that during testing and ideally also at runtime, in order to fall back to the full passthrough mode, using the generic `nm-devices` type.
FR-1898

keyfile: do not try to write out unvalidated YAML (LP: #1952967)

---

netplan/cli/commands/info.py
netplan/cli/commands/migrate.py

Until now, we parsed the YAML configuration at different places in the program:
* libnetplan, where we have most of our business logic, and where we implement data verification
* the `netplan set` command, where we parse the YAML tree to do some syntactical merging of the trees without looking too much into the semantics
* `configmanager.py` + `sriov.py` where we have some business logic to be able to configure the SRIOV backend on the fly.
* `netplan migrate`, which isn't supposed to be used in normal circumstances
Additionally, we use PyYAML in `netplan info` to easily generate well-formed YAML data from a Python dict.
This PR removes the `migrate` and `info` use cases, the other cases will have their own PRs in order to keep review complexity somewhat manageable.
There are a couple of …

Consolidate the YAML parsing into libnetplan: low-hanging fruits (FR-702)

---

src/names.c
src/netplan.c

A couple of patches related to OpenVSwitch handling. The consistency patch is needed to be able to ensure idempotency of the user input (within reason). The type name definition will be needed when we'll rewrite `sriov.py` as we'll need to identify those definitions.

YAML consolidation prelude: OVS handling (FR-702)

---

TODO
doc/netplan.md
src/parse.c
tests/generator/test_errors.py
tests/generator/test_routing.py
tests/integration/routing.py

* Supporting additional route types: anycast, broadcast, local, multicast, nat, throw, xresolve (supported by systemd-networkd as of v243)
* Not assuming a type: unicast, scope: global, by default, but making the default scope depend on the route type:
* local -> host
* nat -> host
* broadcast -> link
* multicast -> link
* anycast -> link
* unicast without gateway/via -> link
* unicast with gateway/via -> global
* global otherwise
This only affects the systemd-networkd backend renderer as for NetworkManager only "unicast" routes are supported.
FR-1798
FR-1078
FR-1077

Improve routing capabilities (LP: #1892272) (LP: #1805038)

---

netplan/cli/commands/set.py
netplan/cli/utils.py
netplan/libnetplan.py
src/abi_compat.c
src/types.c
src/util.c
tests/parser/base.py
tests/test_libnetplan.py
tests/test_utils.py
tests/utils.py

This PR introduces some high-level Python bindings. This is mostly a skeleton that will be populated with the needed elements in later PRs, which will remain in draft state until this one is merged.

YAML consolidation prelude: High-level libnetplan bindings (FR-702)

---

include/netplan.h
netplan/libnetplan.py
src/abi_compat.c
src/netplan.c
src/types.c
src/types.h
src/util-internal.h
src/util.c
src/yaml-helpers.h
tests/test_libnetplan.py

Introduce a couple of APIs that are needed for the various YAML consolidation efforts. Note that this is technically an API break, but the function that is removed has never been part of a release, so this *should* be OK.

YAML consolidation prelude: new YAML dump APIs (FR-702)

---

netplan/cli/commands/get.py
netplan/libnetplan.py
src/netplan.c
src/parse.c
src/types.c
src/types.h
src/util-internal.h
src/util.c
src/yaml-helpers.h
tests/parser/test_keyfile.py
tests/test_cli_get_set.py

Port the `netplan get` command to use the internal YAML generator, originally written for the NM-to-netplan system.
In order to make this work, we had to add a notion of "dirtyness" to the input data, as the user would want their explicit settings displayed even if they match the default value.

YAML consolidation: `netplan get` (FR-702)

---

TODO
doc/netplan.md
netplan/cli/utils.py
src/netplan.c
src/networkd.c
src/parse.c
src/types.h
tests/generator/test_ethernets.py
tests/test_utils.py

The networkd backend, which is the only backend currently supporting driver matches, permits multiple whitespace separated globs. Netplan will happily generate a `.link` file containing the full list of driver globs (which will subsequently work with `networkctl`) but fails to match the driver to the interface itself, meaning the initial apply during boot fails. This is observed with the current Raspberry Pi focal images.
Enhance the handling of `match.driver` to accept a single driver glob (as before) or a sequence of driver globs (new feature).
Example:
```
match:
driver: ["bcmgenet", "smsc*"]
name: en*
```
[LP: #1918421](https://bugs.launchpad.net/ubuntu/+source/netplan.io/+bug/1918421)

Permit multiple patterns for the driver globs in match (LP: #1918421)

---

src/parse.c

The YAML_NO_NODE type marker means that the callback called is via the
`.variable` union field, not `.generic`. Since this is a union type, and
both callbacks have the same signature for now, it works, but future
evolutions of the code will make those signatures evolve independently,
leading to hard-to-debug issues.

parse: fix the handle_match_driver type

---

src/util.c
tests/test_cli_get_set.py

In some cases `netplan get` using the new libnetplan YAML parser would try to insert a `NULL` tag even though the emitter already reached the end and was expecting a `DOCUMENT-END` tag. Check for that condition and handle it.
Also adding a reproducer test case, that is now fixed.
```
File "/home/lukas/canonical/netplan/netplan/cli/commands/get.py", line 72, in command_get
self.dump_state(self.key, np_state, output_file)
File "/home/lukas/canonical/netplan/netplan/cli/commands/get.py", line 57, in dump_state
libnetplan.dump_yaml_subtree(key, tmp_in, output_file=output_file)
File "/home/lukas/canonical/netplan/netplan/libnetplan.py", line 262, in dump_yaml_subtree
_checked_lib_call(lib.netplan_util_dump_yaml_subtree,
File "/home/lukas/canonical/netplan/netplan/libnetplan.py", line 75, in …
```

util: fix dump_yaml_subtree to not insert NULL at the actual end

---

netplan/configmanager.py
tests/test_configmanager.py

`ConfigManager` creates a temporary directory on instantiation and relies on the caller to clean up that temporary directory despite never exposed directly to the caller. Due to the code structure in several places, it would be onerous to call `ConfigManager.cleanup()` everywhere it's needed so this patch instead calls `.cleanup()` whenever the ConfigManager instance is garage collected.
This addresses https://bugs.launchpad.net/netplan/+bug/1959729

Have ConfigManager cleanup its temporary directory on destruction (LP #1959729)

---

doc/netplan.md
examples/sriov.yaml
netplan/cli/commands/__init__.py
netplan/cli/commands/sriov_rebind.py
netplan/cli/sriov.py
netplan/libnetplan.py
src/abi_compat.c
src/generate.c
src/netplan.c
src/parse.c
src/sriov.c
src/sriov.h
src/types.c
src/types.h
src/validation.c
src/validation.h
tests/generator/base.py
tests/test_cli_get_set.py
tests/test_sriov.py
tests/test_utils.py

Certain types of network cards/SmartNICs allow toggling their low-level (`devlink`) embedded switch mode PCI setting in order to utilize the full hardware offloading capabilities. With this PR we're exposing this functionality to the netplan YAML schema:
* `embedded-switch-mode: [switchdev|legacy]`
* choose the devlink setting for the embedded switch (eswitch)
* sticks to the hardware's preset by default
* `delay-virtual-functions-rebind: [false|true]`
* False by default: SR-IOV virtual functions are re-bind to their driver right after setting the eswitch mode
* Can be delayed to a later stage during the boot process; useful when OVS/OVN bonding (VF LAG) is to be used
Example:
```
network:
version: 2
ethernets:
engreen:
embedded-switch-mode: "switchdev"
delay-virtual-functions-rebind: …
```

Enable eswitch mode setting on SmartNICs

---

rpm/netplan.spec

This makes the rpm packaging work with the latest versions of
Netplan and accounts for changes in the RH/Fedora ecosystem.

rpm: Update to latest version and resync with Fedora spec

---

.github/workflows/autopkgtest.patch
.github/workflows/autopkgtest.yml

Working around an issue with `snapd.seeded.service` taking too long to start, delaying the boot and thus failing setup of the test container (`autopkgtest-build-lxc`).
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1878225
Also, disable the unit-tests during autopkgtest build (`DEB_BUILD_OPTIONS=nocheck`) to save some time, we're already running the unit-tests in another Github action.

Fix running the autopkgtests, by working around a LXD issue

---

netplan/cli/commands/apply.py
netplan/cli/utils.py
tests/integration/base.py
tests/integration/bonds.py
tests/integration/regressions.py
tests/test_utils.py

Calling `networkctl_reload()` before `networkd_interfaces()` makes sure that newly created netdevs will show up in the interface list.
Making use of the index number (instead of interface name) ensures that renamed interfaces are properly reconfigured even if they changed their name.
Starting networkd if not active is making sure we can process network changes even if systemd-networkd was stopped before (e.g. by subiquity), see LP#1962095

cli:apply: fix potential race with rename/creation of netdevs and start networkd if off (LP: #1962095)

---

Makefile

Add src/_features.h as dependency for dbus.o to fix the parallel build
failure:
src/dbus.c:17:10: fatal error: _features.h: No such file or directory
Signed-off-by: Yi Zhao <yi.zhao@windriver.com>

Makefile: fix parallel build failure

---

Makefile
README.md
dbus/meson.build
doc/meson.build
examples/meson.build
features_h_generator.sh
features_py_generator.sh
include/meson.build
meson.build
netplan/cli/utils.py
netplan/meson.build
src/meson.build
tests/cli.py
tests/dbus/test_dbus.py
tests/generator/base.py
tests/integration/base.py
tests/integration/bonds.py
tests/integration/bridges.py
tests/integration/ethernets.py
tests/integration/ovs.py
tests/integration/regressions.py
tests/integration/routing.py
tests/integration/run.py
tests/integration/scenarios.py
tests/integration/tunnels.py
tests/integration/vlans.py
tests/integration/wifi.py
tests/parser/base.py
tests/parser/test_keyfile.py
tests/test_libnetplan.py

Adding a Meson build environment in addition to the plain `Makefile` netplan is using currently.
The new build system should be able to support all the Makefile's features and implement them in a more standard conform way. Furthermore, using Meson we'll be able to extend the build-time features more easily in the future, like implementing build-time options and properly acknowledging dpkg buildflags (hardening/LTO/...).
Meson is easy to use, here are some sample commands, to do the usual netplan stuff:
* meson setup build --prefix=/usr [-Db_coverage=true]
* meson compile -C build
* meson test -C build --verbose [TEST_NAME]
* meson install -C build --destdir ../tmproot
All things are done inside the build directory, specified during the `meson setup` command ("build" in the example above), …

Enable building via Meson build system

---

src/dbus.c

Also, increase the default to 10s.
If the caller sees fit to specifiy a 30s timeout for their try call, it
stands to reason to respect that decision, as they (probably) know
better.
This issue came up in the Core testsuite, where the netplan
configuration step failed because `netplan try` took 6s, cf
LP: #1967084. Their DBus call specifies a timeout of 300s, but the call
failed after a "relatively short time", which was this internal timeout.
Note that the mere fact that `netplan try` takes more than 5s on such a
simple configuration is probably due to the following patch:
https://git.launchpad.net/ubuntu/+source/netplan.io/tree/debian/patches/0006-cli-apply-give-some-extra-time-for-networkctl-reload.patch?h=applied/ubuntu/focal-updates
Since the bridge is empty, it might be in a …

dbus: Remove the upper limit on try timeout (LP: #1967084)

---

src/networkd.c
tests/generator/test_routing.py

As of systemd v242 the "GatewayOnlink" spelling was deprecated and replaced by
"GatewayOnLink", while still being available in compat mode.
We've waited long enough and can switch to the proper spelling now.
https://github.com/systemd/systemd/commit/9cb8c5593443d24c19e40bfd4fc06d672f8c554c

networkd: rename GatewayOnlink= to GatewayOnLink=

---

include/netplan.h
include/parse.h
netplan/cli/commands/set.py
netplan/cli/utils.py
netplan/libnetplan.py
src/abi_compat.c
src/error.c
src/netplan.c
src/parse.c
src/types.c
src/types.h
src/util-internal.h
src/util.c
tests/test_cli_get_set.py
tests/test_libnetplan.py

As part of the larger PyYAML cleanup effort, this patch set rewrites the `netplan set` to use libnetplan's own YAML parser instead of PyYAML. This meant enriching the parser to deal with null fields, that need to be tracked out-of-band, as well as creating new APIs to create YAML files out of a Netplan state, with different nuances to match the previous behavior.

YAML consolidation: `netplan set` (FR-702)

---

src/openvswitch.c
tests/generator/base.py
tests/generator/test_ovs.py
tests/integration/ovs.py

`ovs-vsctl` will hang forever if the host is not OVS enabled, blocking the tests. This can especially happen when running tests in a container where the host does not have OVS installed (e.g. ci.debian.net).

Fix infinite timeouts in ovs-vsctl (Closes: #1000137)

---

src/nm.c
tests/parser/test_keyfile.py

The NetworkManager backend should not take a shortcut and skip rendering the password, in case of an unknown WPA type, as that might be overwritten by a passthrough value.

nm: fix rendering of password for unknown/passthrough WPA types (LP: #1972800)

---

Makefile
doc/meson.build

Hello,
In generated manpages, the long options look as if they were prefixed with a single-dash "-", as in the following example:
```
netplan [–debug] generate [–root-dir ROOT_DIR] [–mapping MAPPING]
```
In reality, the double-dash notation was replaced by an en-dash (U+2013) when generating the manpage.
This is caused by the "smart" extension that pandoc enables by default when reading markdown.
Fixed by preventing pandoc from enabling the smart extension when generating manpages. This is only possible when we explicitly specify the input format.
Disabling the smart extension can have a slight impact on how other things like quotes are rendered, but that should not be much of an inconvenience in comparison to the drawbacks that the extension brings.
Thanks,

manpages: fix long options rendered with an en-dash instead of two dash

---

netplan/cli/commands/apply.py
src/generate.c
src/nm.c
tests/generator/base.py
tests/generator/test_auth.py
tests/generator/test_bonds.py
tests/generator/test_bridges.py
tests/generator/test_common.py
tests/generator/test_ethernets.py
tests/generator/test_modems.py
tests/generator/test_passthrough.py
tests/generator/test_vlans.py
tests/generator/test_wifis.py
tests/integration/base.py
tests/integration/ovs.py

By default, `systemd-networkd` controls only interfaces that it has explicitly been configured for (via a sd-networkd `.network` file); it considers other interfaces as "unmanaged" and ignores them. NetworkManager OTOH tries to claim control of any interface that is UP, which might lead to conflicts if multiple networking daemons are used at the same time.
NetworkManager has different ways to control/avoid this behavior:
* `NM_UNMANAGED=1` udev environment, the weakest condition
* NetworkManager.conf `[keyfile].unmanaged-devices=` setting (affected by some unexpected behavior: LP#1615044)
* NetworkManager.conf `[device].managed=` setting, the strongest condition, overruling all other settings, created a runtime in `/run/NetworkManager/devices/*`
The stronger rules via NetworkManager.conf …

Improve NetworkManager's device management/ignore logic, using udev matching rules (LP: #1951653)

---

abi-compat/jammy_0.104.xml
doc/netplan.md
examples/wireless.yaml
netplan/cli/commands/apply.py
src/abi.h
src/netplan.c
src/networkd.c
src/parse.c
src/types.c
tests/generator/test_wifis.py
tests/integration/wifi.py

Allow setting the regulatory domain, using a new `regulatory-domain` setting.
It is implemented in two ways:
* `country=XX` setting in `wpa_supplicant.conf` (networkd/wpasupplicant only)
* oneshot `/run/systemd/system/netplan-regdom.service` calling `iw reg set XX` (works globally)
Example:
```
network:
version: 2
renderer: networkd
wifis:
wlp2s0b1:
regulatory-domain: "GB"
dhcp4: no
dhcp6: no
addresses: [192.168.0.21/24]
access-points:
"MYSSID":
password: 12345678
```

Allow setting the regulatory domain (LP: #1951586)

---

netplan/cli/commands/apply.py
netplan/cli/commands/try_command.py
netplan/cli/utils.py
tests/test_cli_units.py

Catch exception on config error (`LibNetplanException` from the libnetplan YAML parser) to exit gracefully on error, without applying any configuration. Display the parsing error on stderr.
As observed via https://errors.ubuntu.com/problem/2f11b72a6028059267c77dc94cfd3c4028cf58ac

cli: fix crash on LibNetplanException

---

.github/workflows/autopkgtest.yml
doc/examples.md
doc/netplan-yaml.md
examples/vrf.yaml
include/parse.h
netplan/configmanager.py
netplan/libnetplan.py
src/abi.h
src/names.c
src/netplan.c
src/networkd.c
src/nm.c
src/parse.c
src/types.c
src/validation.c
src/validation.h
tests/generator/base.py
tests/generator/test_vrfs.py
tests/integration/routing.py
tests/test_configmanager.py

Adding support for Virtual Routing and Forwarding devices using the sd-networkd and NetworkManager backends.
Any VRF device is linked to a (new) routing table, specified via the `table` stanza and can define its child interfaces via `interfaces: [...]`. If any `routes:` or `routing-policy:` settings are given, those are implicitly connected to the VRF's routing table.
It builds upon #272 (squashed & rebased), extracted VRF bits.
Example:
```
network:
version: 2
[...]
vrfs:
vrf1005:
table: 1005
interfaces:
- br1
- br1005
routes:  # uses "table: 1005" implicitly
- to: default
via: 10.10.10.4
routing-policy:
- from: 10.10.10.42
bridges:
br1:
interfaces: [...]
br1005:
interfaces: [...]
```

Add support for VRF devices (LP: #1773522)

---

netplan/cli/commands/ip.py
tests/cli.py
tests/test_utils.py

Check for NetworkManager leases in `var/lib/NetworkManager/internal-{UUID}-{INTERFACE}.lease` and fallback to `var/lib/NetworkManager/dhclient-{UUID}-{INTERFACE}.lease` if that does not exist. Dhclient is deprecated, but might still be used in some legacy setups.
Also, use some mocking (custom `MockCmd` class, as used elsewhere in our code) to actually run some unit tests on this code and increase the coverage.
The whole code in `ip.py` is pretty old and in bad shape; it should be refactored, but I don't have the time for that right now, just wanted to fix LP#1979674 as a first step.

cli:ip:leases: search for NM's internal DHCP client and dhclient leases (LP: #1979674)

---

doc/examples.md
doc/netplan-yaml.md
examples/vxlan.yaml
src/abi.h
src/names.c
src/names.h
src/netplan.c
src/networkd.c
src/nm.c
src/parse.c
src/types.c
src/types.h
src/util-internal.h
src/util.c
src/validation.c
src/yaml-helpers.h
tests/generator/base.py
tests/generator/test_ovs.py
tests/generator/test_tunnels.py
tests/integration/base.py
tests/integration/tunnels.py
tests/test_configmanager.py

Adding support for VXLAN tunnels using the sd-networkd and NetworkManager backends.
It builds upon #272 (squashed & rebased), extracted VXLAN bits. Applied on top of #285.
Schema according to (internal) spec FO042.
The first 3 commits e83ea8914223841b231843f630eeb382ee18d601 6d3597e356358de2d9a0f8d5e25af3fb27b2e542 02c4f0081ac5cf43adf8300bf49c28865f98d99a are pretty much unrelated to this PR. Those are drive-by fixes that I had been tracking in a separate branch, but the diff is fairly small, so I thought it'd make sense to include them into this PR instead of doing an extra one just for this.
Example:
```
network:
ethernets:
lo:
addresses: [ 192.168.10.10/32 ]
tunnels:
vx1:
mode: vxlan
id: 1
link: lo
mtu: 8950
accept-ra: no
neigh-suppress: true
mac-learning: false
port: 4789
local: …
```

Add support for VXLAN tunnels (LP: #1764716)

---

src/abi_compat.c
src/netplan.c
src/parse-nm.c
src/parse.c
tests/cli.py
tests/generator/base.py
tests/generator/test_args.py
tests/integration/regressions.py
tests/parser/base.py
tests/parser/test_keyfile.py

* add default "wakeonlan" settings for ethernet devices only (NetworkManager 1.40 compat)
* Write YAML files using 0o600 permission
* YAML files written by the user or a (external) tool (e.g. "netplan set", NetworkManager, subiquity, ...) can contain sensitive information (e.g. WiFi passwords), so should stay secret (root/owner read-only).

NetworkManager 1.40 compat & file permission fixes (LP: #1862600, LP: #1997348)

---

netplan/cli/commands/ip.py
src/generate.c
tests/cli.py

When the interface is not defined in the Netplan configuration, the command 'generate --mapping' will return nothing.
Fix for [LP#1996941](https://bugs.launchpad.net/netplan/+bug/1996941)

Fix 'netplan ip leases' crash (LP: #1996941)

---

.coveragerc
.github/workflows/autopkgtest.yml
.github/workflows/build-abi.yml
.github/workflows/check-coverage.yml
Makefile
TODO
meson.build
sitecustomize.py
snap/snapcraft.yaml
tests/dbus/test_dbus.py
tests/generator/test_tunnels.py
tests/generator/test_vlans.py
tests/generator/test_wifis.py
tests/test_cli_units.py
tests/test_terminal.py
tests/test_utils.py

Pytest and pycoverage require some extra configuration to track test coverage in tests that spawn subprocesses. The new files .coveragerc and sitecustomize.py are intended to enable support for subprocesses.
The test set test_terminal.py is completely skipped when testing on my system and, because of that, coverage test was reporting a low coverage. I still need to see it running in our automation to validate if we still need to skip them. Another workaround would be add a nocover to the Terminal class.
Also:
- Fix some deprecation warnings in some tests.
- Remove this task from the TODO list :)

Migrate from (deprecated) nose to pytest

---

src/parse.c
tests/test_libnetplan.py

The filepath isn't being populated for OVS ports netdefs.
Add a unit test to catch this issue.
New unit test outcome without the fix:
```
======================================================================                                                                 
FAIL: test_filepath_for_ovs_ports (test_libnetplan.TestNetDefinition)                                                                                                    
----------------------------------------------------------------------                                                                 
File "/workspace/netplan-filepath/tests/test_libnetplan.py", line 382, in test_filepath_for_ovs_ports
self.assertEqual(os.path.join(self.confdir, "a.yaml"), netdef.filepath) …
```

parse: Add the filepath to OVS ports netdefs

---

include/types.h
include/util.h
src/types-internal.h
src/util.c
tests/ctests/test_netplan_state.c

The Netplan state iterator API is intended to enable consumers to walk through the ordered list of network definitions. It is useful, for instance, when you need to save the netdefs to files but you don't know the netdef ID to lookup for it.
The idea of having a non-opaque struct exposed to consumers was borrowed from Glib ([here](https://github.com/GNOME/glib/blob/abd76e02864163b6a627e5c5722cb4d6a8d35501/glib/ghash.h#L46) and [here](https://github.com/GNOME/glib/blob/abd76e02864163b6a627e5c5722cb4d6a8d35501/glib/ghash.c#L1143)). By doing this, the iterator can be placed at the stack, which is much more convenient.
This API was integrated and tested with the NetworkManager+Netplan integration code base.

Netplan api iterator

---

tests/cli/test_status.py

Some tests were failing in sbuild due to calls to systemctl. It would check if networkd was running and try to start it. In my system the same happens except these tests get stuck asking for my password if I stop networkd.

tests: mock calls to systemctl

---

doc/netplan-set.md

The key should be "addresses" not "dhcp4".

docs: small fix on netplan-set doc

---

src/parse.c
tests/ctests/fixtures/invalid_route.yaml
tests/ctests/fixtures/missing_interface.yaml
tests/ctests/test_netplan_parser.c

If the parsing process finishes with an error, we should return this error instead of assuming it's a missing interface.
For instance, the configuration below will fail with "br0: interface 'ens3' is not defined" when the actual error is "invalid IP family '-1'" due to the invalid IP used as the default route:
```
network:
bridges:
br0:
interfaces:
- ens3
routes:
- to: 0/0
via: 100.64.0.1
ethernets:
ens3: {}
version: 2
```
This PR addresses [LP#2000324](https://bugs.launchpad.net/ubuntu/+source/netplan.io/+bug/2000324)
The configuration above was failing with:
```
$ netplan generate --root-dir /workspace/netplan-issues/fakeroot
/workspace/netplan-issues/fakeroot/etc/netplan/static.yaml:5:11: Error in network definition: br0: interface 'ens3' is not defined
- ens3
^
```
With this change …

parser: return the correct error on failure (LP#2000324)

---

include/util.h
src/error.c
tests/ctests/test_netplan_error.c

api:util: rename netplan_error_clear (from _free) & adopt to nullify
The spec was updated accordingly.
As discussed during the last netplan sync meeting

api:util: rename netplan_error_clear (from _free) & adopt to nullify

---

netplan/cli/commands/apply.py
netplan/cli/ovs.py
tests/integration/ovs.py

If openvswitch is installed but not running, netplan apply will try to call the service anyway and will crash. In this case we probably should ignore the error and log a warning message to the user.
Add an integration test that will be executed by autopkgtest.
It addresses https://bugs.launchpad.net/ubuntu/+source/netplan.io/+bug/1995598
The problem can be reproduced with:
```
lxc launch ubuntu:22.04 jammy --vm
lxc exec jammy bash
apt install openvswitch-switch
systemctl stop ovsdb-server
netplan apply
```

apply: Fix crash when OVS is stopped (LP#1995598)

---

src/networkd.c
tests/generator/test_tunnels.py

If an interface has a list of routes and is linked to a vxlan, the VXLAN keyword is added to the [Route] section in the resulting networkd configuration file.
This change makes the vxlan handling to happen before routes so VXLAN= will be added to the [Network] section.
It fixes [LP#2000713](https://bugs.launchpad.net/netplan/+bug/2000713)
Can be reproduced with:
```
network:
renderer: networkd
ethernets:
eth0:
routes:
- to: 10.20.30.40/32
via: 10.20.30.1
tunnels:
vxlan1:
mode: vxlan
id: 1
link: eth0
```
This is the current output. The VXLAN= keyword was added to the [Route] section.
```
$ cat fakeroot/run/systemd/network/10-netplan-eth0.network
[Match]
Name=eth0
[Network]
LinkLocalAddressing=ipv6
[Route]
Destination=10.20.30.40/32
Gateway=10.20.30.1
VXLAN=vxlan1
```
This is the result …

networkd: make sure VXLAN is in the right section (LP: #2000713)

---

netplan/cli/commands/apply.py
src/nm.c
src/validation.c
tests/ctests/meson.build
tests/ctests/test_netplan_validation.c
tests/ctests/test_utils.h
tests/parser/test_keyfile.py

Netplan will allow the user to enter an interface name that's too long without issues any warning message. The backends will fail to process such an interface with errors like:
```
Jan 17 08:37:31 ubuntu2204 systemd-udevd[176]: eth0: Invalid network interface name, ignoring: anotherverylongname0
```
```
Jan 17 14:17:53 ubuntu2204 systemd-networkd[1019]: /run/systemd/network/10-netplan-notagoodnameforabridge0.netdev:2: Interface name is not valid or too long, ignoring assignment: notagoodnameforabridge0
Jan 17 14:17:53 ubuntu2204 systemd-networkd[1019]: NetDev without Name= configured in /run/systemd/network/10-netplan-notagoodnameforabridge0.netdev. Ignoring
```
Also, netplan apply will crash when trying to rename the interface:
```
oot@ubuntu2204:~# netplan apply
Traceback (most recent …
```

Check if the interface name is too long (LP: #1988749)

---

doc/examples.md
doc/netplan-yaml.md
examples/direct_connect_gateway_ipv6.yaml

Hi,
When the on-link flag is enabled, the additional route has no effect. This extra route is only required when the on-link flag is *not* set.
Indeed, for netorkd, when "on-link" is true, the resulting systemd-networkd config file contains "GatewayOnLink=true", which translates to "flags: onlink" in its logs. The resulting route appears with this "onlink" flag in the output of "ip route".
Similarly, for NetworkManager, "route1_options=onlink=true" gets added by
https://github.com/canonical/netplan/blob/e5ff9f6dbeb20a8a3e6abc712efcf1b0008afa75/src/nm.c#L228-L230

doc/examples: remove unnecessary route for IPv6 on-link gateways

---

include/parse.h
netplan/cli/commands/set.py
netplan/libnetplan.py
src/generate.c
src/netplan.c
src/parse.c
src/types-internal.h
src/types.c
src/util.c
tests/cli/test_get_set.py
tests/ctests/test_netplan_parser.c

This PR solves multiple issues in `netplan set`. First, deletion of origin-hint files on update (i.e. if the netdef is already contained inside the origin-hint file). This happens when repeatedly calling netplan set on the same origin-hint and netdef, e.g.:
```
Starting with an empty Netplan config in /etc/netplan:
$ netplan set --origin-hint test "bridges.br54.dhcp4=false"
=> will create test.yaml, containing the br54 definition
$ netplan set --origin-hint test "bridges.br54.dhcp4=true"
=> updating the same br54 netdef (re-using 'netplan set') will delete test.yaml
```
This is fixed by the first commit:
* 8931bf367b4c5185c67113da05668c34eb190562 generate:util: fix double-slash root filepath
Next, when parsing the full YAML hierarchy, stanza updates might be siphoned away, as the same …

cli:set: update only specific origin-hint if given (LP: #1997467)

---

.github/workflows/check-address-sanitizer.yml
examples/bonding.yaml
examples/direct_connect_gateway.yaml
examples/direct_connect_gateway_ipv6.yaml
examples/static_singlenic_multiip_multigateway.yaml
examples/wireguard.yaml
tools/run_asan.sh

Add an script that can be used to run the netplan binaries and check for memory issues and a github action to call this script.
I added it to a directory called "tools" because it can be useful during development.

Memory leak action

---

src/parse.c
src/util-internal.h
src/util.c
tests/ctests/test_netplan_misc.c
tests/generator/test_routing.py

We currently check if the number of routes we have in the list is the same as the number of entries in the yaml structure. This cause problems when routes come from different files, see LP#2003061. In this case, the second route is not added to the netdef.
This patch changes the logic to actually check if the route being processed is already in the list. For the uniqueness check, it compares the route IP family, table ID, metric, from, to and via fields.

parser: check for route duplicates (LP: #2003061)

---

tests/integration/base.py

Make sure NetworkManager's `unmanaged-devices` are kept in check so that NM does not take control over some network interfaces that are controlled by the test system, such as the routers veth42, veth42, fake wifi AP, ...
Replaces the "autopkgtest-fixes.patch" Distro patch.
Changing the location of the denylist from /run to /etc because the changes in /run would be overwritten by our test system's /etc/NetworkManager/conf.d/90-test-ignore.conf, because /etc/ drop-in configs are read after /run/ drop-ins and the /etc/ drop-in uses a hard overwrite of `unmanaged-devices=...` in order to reset the system's default in /usr/lib/NetworkManager/conf.d/10-globally-managed-devices.conf (guess we could also downgrade the test systems static /etc/ drop-in to /run/ which should have the same effect). …

tests:base:ethernets: Improve stability of autopkgtests

---

Makefile
abi-compat/suppressions.abignore
meson.build
src/util-internal.h
src/util.c
tests/ctests/meson.build
tests/ctests/test_netplan_deprecated.c
tests/ctests/test_netplan_error.c
tests/ctests/test_netplan_misc.c
tests/ctests/test_netplan_parser.c
tests/ctests/test_netplan_state.c
tests/ctests/test_netplan_validation.c
tests/test_libnetplan.py

This function has been calling into the python 'netplan set' command for historical reasons. We can now stay internal to libnetplan and execute the corresponding libnetplan functions directly.
Basically, we're now implementing inside this function in `util.c` what has previously been executed via `netplan/cli/commands/set.py`

API: update netplan_delete_connection() to avoid spawning another process

---

meson.build
rpm/netplan.spec
src/meson.build

This pull request fixes Netplan to build on Fedora Linux and updates the RPM packaging to use the Meson build.

Fix FTBFS on Fedora and refresh RPM packaging

---

src/parse.c
tests/generator/test_bonds.py
tests/parser/test_keyfile.py

This field should accept only the values "fast" and "slow". It's documented in the Netplan documentation.
It addresses LP: #1745648
Note: although we have it documented that the expected values are "fast" and "slow", NetworkManager also accepts 1 and 0, respectively, besides the keywords. There is a chance that someone out there is using NetworkManager as renderer and the values as numbers and it is just working fine. Should we handle the case and also accept 1 and 0? In this case, we would simply forward the value to NM and translate it to text before generating the configuration for networkd.

ATTN: parser: validate lacp-rate properly (LP: #1745648)

---

netplan.completions
tools/completely.yaml

The file was (lazily) regenerated using the completely tool [0].
In the future we could do that in netplan itself using what we add to the argparse instance.
[0] - https://github.com/DannyBen/completely
In the future we could try to add a builtin command similar to what `kubectl completion` does and generate the script using argparse as source of information. Something like `netplan completion [bash|zsh]`.

Add all the commands to the bash completion file (LP: #1749869)

---

meson.build
src/meson.build
tools/meson-make-symlink.sh

meson: use meson-make-symlink.sh helper script instead of install_symlink()
This will allow to dynamically adopt the symlinks for usrmerged and non-usrmerged installations, especially:
root@ll:~# pkgconf --variable=systemdsystemgeneratordir systemd /lib/systemd/system-generators
[root@f37 ~]# pkgconf --variable=systemdsystemgeneratordir systemd /usr/lib/systemd/system-generators
Helper script inspired by util-linux 238.1-5 (tools/meson-make-symlink.sh)
Related to #323

meson: use meson-make-symlink.sh helper script instead of install_symlink()

---

netplan/cli/ovs.py

Fix typo from  'unkown' to 'unknown'

netplan: cli: fix typo from 'unkown' to 'unknown'

---

doc/netplan-yaml.md
src/parse.c
tests/generator/test_ovs.py

parse:ovs: Ignore deprecated OpenFlow1.6 protocol (LP: #1963735)
The OpenFlow 1.6 draft got abandoned by the ONF as of OVS v2.12:
https://www.openvswitch.org/releases/NEWS-2.12.0.txt

parse:ovs: Ignore deprecated OpenFlow1.6 protocol (LP: #1963735)

---

src/dbus.c
tests/integration/dbus.py
tests/integration/regressions.py

Dbus Config()/Get() were not working due to a missing / in the destination path.
We still need a nice integration test to catch this issue.
```
sudo dbus-send --system --print-reply --type=method_call --dest=io.netplan.Netplan /io/netplan/Netplan io.netplan.Netplan.Config
From dbus-monitor:
string "Failed to copy file /etc/netplan/01-network-manager-all.yaml -> /run/netplan/config-1YXM01etc/netplan/01-network-manager-all.yaml: Error opening file “/run/netplan/config-1YXM01etc/netplan/01-network-manager-all.yaml”: No such file or directory
```
The path is malformed: `/run/netplan/config-1YXM01etc/netplan/01-network-manager-all.yaml`

dbus: Build the copy path correctly

---

.github/workflows/spread.yml
spread.yaml
src/meson.build
tests/spread/dbus/task.yaml
tests/spread/snapd-integration/task.yaml

This is a first draft of adding integration tests for netplan with snapd and dbus. It uses spread and the LXD backend to run inside the github runners. A first test is designed to do basic interactions between netplan and snapd.
I put this into "draft" mode because I ran into the following issues:
1. following the instruction to make crashes meson inside a 22.04 container (https://paste.ubuntu.com/p/qRnJvjyddN/)
2. when commenting out the testing the install step fails with: 
```
meson install -C build --destdir=/
...
Installing /home/tests/netplan.completions to //usr/share/bash-completion/completions
ERROR: Tried to install symlink to missing file //lib/netplan/../../usr/libexec/netplan/generate
```
I suspect (2) is a result in the most recent …

tests: add new spread based snapd integration test

---

doc/cli.md
doc/manpage-footer.md
doc/meson.build
doc/netplan-info.md
doc/netplan-ip.md
doc/netplan-rebind.md
doc/netplan-status.md
doc/netplan-yaml.md

Adding man pages for all the commands.
Improving the network types descriptions a little.
Follow-up for #333

Netplan docs rework (Part 2)

---

Makefile
netplan/cli/commands/apply.py
netplan/cli/commands/ip.py
netplan/cli/commands/status.py
netplan/cli/ovs.py
netplan/cli/utils.py
tests/cli/test_status.py
tests/generator/base.py
tests/generator/test_args.py
tests/integration/base.py
tests/integration/bridges.py
tests/integration/dbus.py
tests/integration/ethernets.py
tests/integration/ovs.py
tests/integration/regressions.py
tests/integration/routing.py
tests/integration/tunnels.py
tests/integration/wifi.py
tests/netplan_dbus/test_dbus.py
tests/parser/base.py
tests/test_ovs.py

Cleanup a few basic things like:
* using `shutil.rmtree()` over `rm -rf` subprocess call
* clean up all the coverage data from the Makefile (`make clean`)
* Use the more readable `text=True` alias to subprocess calls (over `universal_newlines=True`) – it's available since Python 3.7
* Improve parameter passing to `networkctl`, accounting for network interfaces names that contain a leading `-`

Some refactoring

---

netplan/libnetplan.py

It says it's 1MB but the value is actually 1GB

netplan: adjust the maximum buffer size to 1MB

---

src/util.c

Strings starting with "-" will be interpreted as systemd-escape parameters.
Like in:
```
network:
wifis:
'--version':
access-points:
aasasd:
password: "asdasdasdasd"
```
```
$ ./build/src/generate --root-dir /tmp/fakeroot3/
ERROR: cannot create file /run/systemd/system/netplan-wpa-systemd 252 (252.5-2ubuntu3)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified.service: Failed to create file “/tmp/fakeroot3/run/systemd/system/netplan-wpa-systemd 252 (252.5-2ubuntu3)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL …
```

parse: use "--" with systemd-escape

---

src/validation.c
tests/generator/test_vrfs.py

vrfs: skip policies parsing if list is NULL (LP: #2016427)

---

src/networkd.c

Believe or not, it was found with this https://github.com/daniloegea/netplan-fuzz :eyes:

networkd: plug a memory leak

---

src/nm.c
tests/generator/test_errors.py

When routes validation fails we should return. It's also hitting an assertion later because the "error" object is already built:
```
(generate:246468): GLib-CRITICAL **: 09:45:27.526: g_key_file_save_to_file: assertion 'error == NULL || *error == NULL' failed
```

nm: return if write_routes() fails

---

src/parse.c

The key doesn't need to be duplicated before being passed to g_datalist_set_data_full. It will not be freed.

parse: plug a memory leak

---

src/parse.c
tests/ctests/test_netplan_parser.c

By definition, the renderer on nm-devices must be NetworkManager. Not defining it will default to networkd. Apart from the fact it doesn't make sense, it is causing a memory leak because the function g_datalist_clear() will no be called in reset_backend_settings() if the backend is not NM.

parse: set the backend on nm-devices to NM by default

---

netplan/libnetplan.py
tests/test_libnetplan.py

Also, enable the dump_yaml() API to dump the data to a StringIO object.

Add a netplan_parser_load_keyfile() Python binding

---

src/nm.c
src/validation.c
tests/generator/test_tunnels.py

As #350 became more complex than anticipated, I'm creating a separate PR for the wireguard part.

Wireguard fixes

---

src/abi.h
src/netplan.c
src/nm.c
src/parse-nm.c
src/parse.c
src/types.c
src/validation.c
tests/generator/test_passthrough.py

Fix a memory leak, an assert and an error message

---

netplan/cli/commands/apply.py
src/openvswitch.c
src/parse.c
tests/generator/test_ovs.py
tests/integration/ovs.py

I found it thanks to a memory leak. If both peers have the same name, the netdef will end up with a `netdef->peer_link` pointing to itself and `netdef->link` strdup'ed twice.

ovs: don't allow peers with the same name

---

doc/conf.py
doc/requirements.txt

This plugin will allow our YAML examples to be easily copied by the reader of our documentation.

doc: make us of sphinx copybutton plugin

---

.github/workflows/autopkgtest.yml

This will set up LXD with proper permissions and adopt the firewall rules to accommodate for the pre-installed docker application, e.g.: https://discuss.linuxcontainers.org/t/9953/4

CI: make use of the canonical/setup-lxd action

---

.readthedocs.yaml

The RTD build is failing due to a new version of urllib3. According to [1], this change should fix the problem.
[1] - https://github.com/readthedocs/readthedocs.org/issues/10290

rtd: set the OS and Python versions explicitly

---

src/parse-nm.c
tests/parser/test_keyfile.py
tools/keyfile_to_yaml.py

See [LP: #2016625](https://bugs.launchpad.net/netplan/+bug/2016625) for more details.
I'm also including a little tool that was useful during investigation and tests.

Fix 8021x eap method parsing (LP: #2016625)

---

.github/workflows/autopkgtest.yml
.github/workflows/spread.yml

There is a bug in canonical/setup-lxd@v0.1.0 where the `channel` input is ignored. This has been fixed in v0.1.1. See https://github.com/canonical/setup-lxd/pull/8

CI: update canonical/setup-lxd to v0.1.1

---

doc/netplan-yaml.md
src/abi.h
src/names.c
src/nm.c
src/parse-nm.c
src/validation.c
tests/ctests/meson.build
tests/ctests/test_netplan_keyfile.c
tests/ctests/test_utils_keyfile.h
tests/generator/test_tunnels.py
tests/parser/test_keyfile.py

Support for Wireguard keyfiles parsing is required to get the new Network Manager autopkgtests passing [1]. The original plan was to add support only for WG, but I ended up including all tunnel types.
There is a not-so-nice function renaming in src/parse-nm.c that was required to get new ctests compiling.
[1] - https://code.launchpad.net/~danilogondolfo/network-manager/+git/network-manager/+merge/443011

keyfile parser: add support for all tunnel types (LP: #2016473)

---

.github/workflows/autopkgtest.yml

After adding the new tag from the stable/0.106 branch, dch is failing with:
New version specified (0.106-78-g3074070) is less than
the current version number (0.106.1-0ubuntu1)!  Use -b to force.
Basically, git describe is still describing the tag 0.106 and not 0.106.1.
With this change, we'll first find the lastest tag before calling describe.

CI: fix dch after adding the new 0.106.1 tag

---

include/types.h
netplan/cli/commands/generate.py
netplan/cli/core.py
netplan/cli/sriov.py
netplan/cli/utils.py
netplan/configmanager.py
netplan/libnetplan.py
src/error.c
src/netplan.c
src/networkd.c
src/nm.c
src/openvswitch.c
src/parse.c
src/sriov.c
src/util.c
src/validation.c
tests/cli/test_get_set.py
tests/cli/test_units.py
tests/parser/base.py
tests/test_libnetplan.py
tests/test_sriov.py
tests/test_utils.py

libnetplan doesn't differentiate each type of error very well. It impacts mainly its frontend where we rely on error message interpretation to tell the user what happened.
As we are planning to offer the Python bindings as a module that will be consumed by others, such as cloud-init, it's important to improve the API error handling.
This RFC incorporates the ideas from #318 and defines specific libnetplan errors and exception for each type with some details.
Originally, this PR was intended to improve error handling to fix issues like the ones mentioned below (which is still addressed).
--------
Old description (still valid):
When netplan get or set fails for some reason, due to bad inputs or file permissions for example, netplan will crash. This handles these situations gracefully. …

netplan: Handle command exceptions

---

examples/wireless_adhoc.yaml
src/networkd.c
tests/generator/base.py
tests/generator/test_wifis.py

generated configuration for wpa_supplicant is missing "frequency", when in adhoc mode.
here is the corresponding bug report:
https://bugs.launchpad.net/netplan/+bug/2020754

Provide frequency to wpa_supplicant when in adhoc mode (LP: #2020754)

---

src/parse.c
tools/keyfile_to_yaml.c
tools/run_asan.sh

Now the run_asan.sh script will call the generator twice for each yaml file, once with renderer=networkd and again with renderer=NetworkManager.
When the renderer is set to NetworkManager, it will also call a new tool (keyfile_to_yaml.c) to load the keyfile.
Also, plug two memory leaks :)

Improve the coverage of the memory leak tests

---

src/parse-nm.c
tests/parser/base.py
tests/parser/test_keyfile.py

Network Manager allows entering IPs without prefixes. Although WG docs says the format a.b.c.d/prefix should be used, it will accept only the IP address and default the prefix to /32. This change will append a /32 to the allowed IPs that don't have a prefix found in the keyfile.

Fix keyfile parsing of wireguard config when the prefix of allowed IPs is omited

---

src/networkd.c
src/nm.c
src/validation.c
tests/generator/test_routing.py

Routes metric are rendered as signed integer instead of unsigned integer. This means all metric > 2147483647 is rendered as negative and is breaking the generated configuration.
https://bugs.launchpad.net/netplan/+bug/2023681
- [-] New/changed keys in YAML format are documented.
- [-] \(Optional\) Adds example YAML for new feature.
- [-] \(Optional\) Closes an open bug in Launchpad.

routes: fix metric rendering (LP: #2023681)

---

.woke.yaml
abi-compat/suppressions.abignore
doc/netplan-yaml.md
examples/dummy-devices.yaml
include/types.h
src/names.c
src/networkd.c
src/nm.c
src/parse-nm.c
src/parse.c
tests/generator/base.py
tests/generator/test_dummies.py
tests/integration/dummies.py
tests/parser/test_keyfile.py

This is a resurrection of #115. I didn't reuse the PR because it's old and incomplete.
It implements support for parsing YAMLs and Keyfiles so it works with netplan-everywhere (Network Manager + Netplan).
Related LP bug: https://bugs.launchpad.net/netplan/+bug/1774203
Unfortunately the Linux kernel name for this type of interface conflicts with our sensitive-wording  policy so I had to add some annotations in the code to ignore the errors from Woke. Our words list doesn't catch the word 'dummies' though (flaw I exploited to not insert the wokeignore annotation on some places), so I don't know, maybe we could just drop "dummy" from our denylist...

Add support for "dummy" interfaces (LP: #1774203)

---

.github/workflows/autopkgtest.yml
.github/workflows/debci.yml

This is running on Debian testing inside a raw LXC container and should resemble the ci.debian.net migration pretty closely.

CI: add DebCI integration test

---

src/parse-nm.c

parse-nm:wg: add support for reading the listen-port property

---

include/types.h
src/netplan.c
src/nm.c
src/parse-nm.c
src/parse.c
tests/generator/test_vlans.py
tests/parser/test_keyfile.py

Support for reading VLAN keyfiles.
One problem found during the implementation is that Netplan requires the existence of the `link` interface in the YAML configuration. Although Network Manager can create a vlan connection even if the parent interface doesn't exist.
The approach used here basically makes netplan to behave the same way: when the renderer is NetworkManager, it will ignore the fact that the parent doesn't exist and point to whatever interface was used by NM. In order to continue passing the VLAN validation rules, the netdef type `NETPLAN_DEF_TYPE_NM_PLACEHOLDER_` was introduced. It will be used in cases where a required dependency can't be satisfied but it's still required by Netplan but not by Network Manager. So its use is basically to fill this gap and allow the backend …

Vlan keyfile parser support

---

.github/workflows/network-manager.yml

We're testing NetworkManager from mantic-proposed against a local build of netplan.io from this repository.
So far we can only run NetworkManager's autopkgtests which allow for 'isolation-container'.
FR-4415

CI: initial NetworkManager autopkgtests

---

doc/explanation.md
doc/nm-all.md

This adds an explanation section to Netplan's docs, about the `/usr/lib/netplan/00-network-manager-all.yaml` default configuration:
```yaml
network:
version: 2
```
Replaces: https://github.com/canonical/netplan/pull/373
See also: https://github.com/canonical/netplan.io/pull/273

doc: Explanation about 00-network-manager-all.yaml

---

tests/integration/base.py
tests/integration/regressions.py
tests/integration/tunnels.py

Starting with the systemd v253 update NetworkManager started taking
implicit control of certain interfaces, blocking itself (after a restart)
from managing those interface through its configure netplan-* connection
profile.
https://bugs.debian.org/1039071
iproute2 v6.4 changed its CLI output, the JSON output is expected to
stay stable, so we should migrate to using iface_json() over time.
https://bugs.debian.org/1040004
Also, resolves a race condition where the following text is already gone from the buffer at the time when we check the assertions. We see such failures a lot in the Ubuntu autopkgtests:
```
Do you want to keep these settings?
Press ENTER before the timeout to accept the new configuration
Changes will revert in {} seconds
```

Improve autopkgtest stability with systemd 253 & iproute 6.4

---

meson.build
src/abi.h
src/dbus.c
src/error.c
src/generate.c
src/names.c
src/networkd.c
src/nm.c
src/parse-nm.c
src/parse.c
src/sriov.c
src/types-internal.h
src/types.c
src/util-internal.h
src/util.c
src/validation.c
tests/ctests/test_netplan_deprecated.c
tests/ctests/test_netplan_error.c
tests/ctests/test_netplan_keyfile.c
tests/ctests/test_netplan_misc.c
tests/ctests/test_netplan_parser.c
tests/ctests/test_netplan_state.c
tests/ctests/test_netplan_validation.c

Some of this issues were found when I tried to compile netplan as c++, some were found by increasing the warning level with `-Wextra` and some were found by me while fixing the issues found by the compiler.
Some changes might seem unnecessary, specially the one annotating unused parameters with `__unused`. But I think they add some value.
My motivation to increase the warning_level to 2 is to avoid problems like this:
```c
int main() {
int a = -1;
unsigned int b = 1;
if(a > b) {
printf("According to my calculations %d IS greater than %d\n", a, b);
}
}
```
```
$ cc main.c
$ ./a.out
According to my calculations -1 IS greater than 1
``` 
It's unfortunate that it's only caught by the compiler by using `-Wextra` or explicitly using `-Wsign-compare` (which is enabled by `-Wextra`).
Annotating …

Fixes for minor issues

---

tests/integration/ethernets.py
tests/integration/scenarios.py
tests/integration/vlans.py

systemd-networkd v245 seems to be more picky about moving an interface from "configuring" to "configured" state. It waits for an IPv6 RA to be received. So we need to define "accept-ra: false" in Netplan tests to ignore that, or make our test environment (dnsmasq) to actually provide RAs. I went with the latter.
We still see weird error messages from 'networkctl', which seems new, but they do not fail tests. E.g.: Failed to query link bit rates: Invalid argument
Failed to query link DHCP leases: Invalid argument
I have the impression that those error messages are thrown while the interface is still in "configuring" state, i.e. while waiting for the RA to be received/processed. We're calling 'networkctl status IFACE' in a loop and the error message vanishes when calling the command after a …

tests:integration: Adopt for systemd v254 (Closes: #1041310)

---

src/parse.c

With the NetworkManager integration in place there will be many more cases where "nm-devices" are used, and we don't want to spam system logs with our warnings.

parse: Downgrade NM passthrough warning to debug

---

src/netplan.c
tests/cli/test_get_set.py

The "unlink" part at the bottom of netplan.c:netplan_state_update_yaml_hierarchy seems to ignore any global values (such as "renderer") and operates on files containing netdefs only.
The issue is happens due to a combination of the following PRs: https://github.com/canonical/netplan/pull/254 https://github.com/canonical/netplan/pull/299
Which got SRUed into Jammy via 0.105-0ubuntu2~22.04.2
Here's a minimal reproducer:
```
netplan set network.renderer=NetworkManager --origin-hint=00-no-netdefs-just-globals
netplan set network.ethernets.eth99.dhcp4=true --origin-hint=90-some-netdefs
ls -l /etc/netplan/
netplan set network.ethernets.eth99=NULL
cat /etc/netplan/00-no-netdefs-just-globals.yaml
```
FR-4793

netplan.c: Don't drop files with just global values on 'set' (LP: #2027584)

---

doc/netplan-yaml.md
src/abi.h
src/names.c
src/names.h
src/netplan.c
src/nm.c
src/parse-nm.c
src/parse.c
src/types.c
src/validation.c
tests/generator/test_tunnels.py
tests/parser/test_keyfile.py

Network Manager supports storing the Wireguard private key in an external keychain agent, like the kdewallet. In this cases, it will emit the following configuration in the keyfile: `wireguard.private-key-flags=1` and omit the private key, which will be stored somewhere else.
The new key will look like this:
```yaml
network:
version: 2
tunnels:
wg-tunnel:
addresses:
- "10.20.30.1/24"
mode: "wireguard"
port: 51820
keys:
private-key-flags:
- agent-owned
```
Adding this options is one way of solving the issue described here https://bugs.launchpad.net/ubuntu/+source/netplan.io/+bug/2024661

NetworkManager: Wireguard private key flag support

---

src/abi_compat.c
src/netplan.c
src/networkd.c
src/nm.c
src/openvswitch.c
src/parse-nm.c
src/parse.c
src/util.c
src/validation.c
tests/ctests/meson.build
tests/ctests/test_netplan_keyfile.c
tests/ctests/test_netplan_nm.c
tests/ctests/test_netplan_openvswitch.c
tests/test_libnetplan.py

This PR addresses some issues found via static analysis by the Coverity tool.
FR-3484

Fixing Coverity issues

---

meson.build

Python-coverage 7.x changed the pattern matching behavior for filesystem paths.

tests: fix test coverage report with newer python-coverage

---

.github/workflows/coverity.yml

It will run every Monday and automatically upload the results.
The token and email needed are stored as Github secrets.
Example of execution: https://github.com/daniloegea/netplan/actions/runs/5821712154/job/15784716385

github: add a scheduled action to run Coverity

---

doc/netplan-yaml.md
examples/virtual-ethernet.yaml
include/types.h
src/abi.h
src/names.c
src/netplan.c
src/networkd.c
src/nm.c
src/parse-nm.c
src/parse.c
src/types.c
src/validation.c
src/validation.h
tests/generator/base.py
tests/generator/test_veths.py
tests/integration/veths.py
tests/parser/test_keyfile.py

Veths are Virtual Ethernet interfaces that are commonly used to
connect bridges or network namespaces. They act like a link between
two networks, simply bypassing traffic from one veth peer to the other.
Veths work in peers, meaning that users will always create two of them.
This implementation allows users to create peers of veths, configure them with
IPs, routes and etc, change their MAC addresses and use them as member
interfaces for bridges and bonds for example. It doesn't support adding veths
to different network namespaces, although it could be done by an external tool.
As both peers are configurable with IPs and etc, they must be defined in
separate stanzas.
A new type of network called `virtual-ethernets` was created and one extra key called 
`peer` was introduced.
```yaml …
```

Support for VETH interfaces

---

.github/workflows/coverity.yml

Also, get the project version dynamically using meson introspect.

github: only run the coverity workflow on our repository

---

src/parse.c
src/util.c

Addressing CIDs 398341, 398340 and 398338.

Addressing a few issues found by coverity

---

netplan_cli/cli/commands/status.py
tests/cli/test_status.py

cli:status: Make rich pretty printing optional
To avoid a hard dependency on python3-rich
E.g. needed for stable series SRUs (like Jammy), which don't support python3-rich in `main`

cli:status: Make rich pretty printing optional

---

include/netplan.h
python-cffi/netplan/_build_cffi.py
python-cffi/netplan/netdef.py
src/types-internal.h
src/util-internal.h
src/util.c
tests/test_libnetplan.py

Add a property to retrieve the macaddress field from the netdef.
Refactor the addresses iterator to comply with our naming standards as advised in the PR #386 code review.
Add iterators for DNS nameservers and search domains following the naming standards as mentioned above.

Expose macaddress and DNS configuration from the netdef

---

python-cffi/netplan/_build_cffi.py
python-cffi/netplan/netdef.py
src/types-internal.h
src/util-internal.h
src/util.c
tests/test_libnetplan.py

I created the NetplanRoute class as a dataclass but I'm not convinced it's a good idea... I feel like it's better to assign each property separately without an `__init__` method...

libnetplan: expose the routes list in the netdef

---

src/parse-nm.c
tests/parser/test_keyfile.py

parse-nm: add support for VRF devices

---

src/parse.c
tests/integration/routing.py

This is to fix test failures with latest NetworkManager v1.44, after they slightly changed behavior:
https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/commit/dabfa26a41edc7911a45a4689d555e8f055b0373

parse: allow COMMON_LINK_HANDLERS for VRFs (LP: #2031421, Closes: #1049432)

---

.github/workflows/autopkgtest.yml
.github/workflows/coverity.yml
.github/workflows/debci.yml
.github/workflows/network-manager.yml

Changes:
- Coverity: fetch tags before trying to use them
- Autopkgtests: use my network-manager PPA temporally with the fix for veths
- Autopkgtest/debci/network-manager ci: fix the workflows after the python3-netplan split

GitHub CI fixes

---

src/networkd.c
src/parse.c
tests/generator/test_auth.py
tests/generator/test_wifis.py

When using WPA-PSK and defining the password without the "auth" section, enable support for both WPA2 and 3 Personal. This will set the support for Protected Management Frames to optional implicitly.

wifi: support WPA2 and WPA3 Personal simultaneously

---

src/util.c
tests/test_libnetplan.py

Tripped on this while working on netplan diff. We probably want to patch the netplan package as well.
```
File "/root/netplan/tools/diff.py", line 117, in <module>
diff = diff_state.get_diff()
^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/netplan/netplan_cli/cli/state_diff.py", line 149, in get_diff
full_state = self.get_full_state()
^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/netplan/netplan_cli/cli/state_diff.py", line 103, in get_full_state
device_type = DEVICE_TYPES.get(config.type, 'unknown')
^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/netplan/netdef.py", line 118, in type
return ffi.string(lib.netplan_def_type_name(lib.netplan_netdef_get_type(self._ptr))).decode('utf-8')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```

util: don't return a placeholder netdef in the iterator

---

src/networkd.c
src/nm.c
src/validation.c
tests/generator/test_tunnels.py
tests/integration/tunnels.py

The "local" IP property is not required by backends so we shouldn't error out if it's not defined.
Tracking LP bug https://bugs.launchpad.net/ubuntu/+source/netplan.io/+bug/2034067

tunnels/validation: do not error out if "local" is not defined

---

src/parse-nm.c
src/parse.c
tests/generator/test_tunnels.py
tests/parser/test_keyfile.py

The Network Manager GUI will emit 'Endpoint=' if it's not specified when creating the tunnel. libnetplan is generating 'endpoint: ""' in this case and the parser is returning an error.
In nm-parse, if Endpoint is either empty or NULL we'll just not read it. In the parser, if we find 'endpoint: ""', we'll just ignore it as if it were not defined.
See LP: #2038811

wireguard: ignore empty endpoints (LP: #2038811)

---

netplan_cli/cli/commands/try_command.py
src/nm.c

When the Netplan systemd generator runs before the NetworkManager service, Netplan will preempt NetworkManager from creating folder '/run/NetworkManager' and will assign it permissions 700.
This is a side effect of the call to umask in function write_nm_conf_access_point, made to restrict the permissions on subfolder '/run/NetworkManger/system-connections'. A regular user needs to read from /run/NetworkManager where, in some systems, files such as resolv.conf ultimately reside.
In my Yocto image /etc/resolv.conf  is a symlink to /etc/resolv-conf.NetworkManager itself to /run/Netw
orkManager/resolv.conf.  Because the /run/NetworkManager folder created by Netplan has 700 permissions a regular user has no access to resolv.conf which breaks domain name resolution.
This fix assigns the proper …

Fix permissions on folder '/run/NetworkManager/'

---

src/abi.h
src/netplan.c
src/networkd.c
src/nm.c
src/parse-nm.c
src/parse.c
src/types.c
src/util-internal.h
src/util.c
tests/generator/test_wifis.py
tests/parser/test_keyfile.py

Originally, Netplan assumes the PSK and 802-1x identity password will
not be used simultaneously.
With this change, when both passwords are used, the PSK is expected to
be placed in "ssid".password and the identity in "ssid".auth.password.
"ssid".auth.password can also be used by the PSK if it's the only password.
When 802-1x is used, the PMF setting will not be emitted if the PSK is
also present. NM will error out if both settings are used simultaneously.
It also copes with unsupported EAP methods.
Here are some test cases that are currently leading to NM crashes:
```
nmcli con add type wifi ifname wlan0 ssid asdasd wifi-sec.key-mgmt wpa-psk wifi-sec.psk asdasdasd 802-1x.eap md5 802-1x.identity username 802-1x.password aaaaaaaa
```
```
nmcli con add type wifi ifname wlan0 ssid asdasd …
```

wifi: make it possible to have a psk and an eap password simultaneously

---

netplan_cli/cli/state.py
netplan_cli/cli/state_diff.py
netplan_cli/meson.build
python-cffi/netplan/netdef.py
tests/cli/test_state_diff.py
tests/integration/diff.py
tools/diff.py

This is the first iteration of the `diff` feature. At the moment, only a few number of resources are analyzed:
1) IP Addresses
2) DNS nameserver and search domains
3) Routes
4) MAC addresses
5) Missing interfaces
A number of heuristics were used to eliminate configuration we don't want to compare. These are basically settings that are very likely assigned automatically, such as IPs and routes assigned via DHCP. The reason for that is that this information will not be found in Netplan.
For example: if the interface has `dhcp4` enabled and an empty list of addresses in Netplan, we don't report to the user that the IP that is assigned, via DHCP, to that interface in the system is not present in Netplan. We do report though the case where the interface has no IPs but DHCP is enabled in …

Netplan state diff

---

src/networkd.c
tests/generator/test_common.py

With systemd-v243 (which is the default since focal), the "CriticalConnection" attribute was
revamped into "KeepConfiguration" [1], addressing several issues, especially in high-availability
environents [2][3].
This PR is preparatory work for #409 
If I understand the code correctly, it still uses "CriticalConnection" when setting "critical: true" in the netplan configuration.
- [1] https://github.com/systemd/systemd/pull/12511/files
- [2] https://github.com/systemd/systemd/issues/12050
- [3] https://chr4.org/blog/2019/01/21/make-keepalived-play-nicely-with-netplan-slash-systemd-network/
Closes: https://bugs.launchpad.net/netplan/+bug/1896799
- [] New/changed keys in YAML format are documented.
- [] \(Optional\) Adds example YAML for new feature.

Migrate CriticalConnection (deprecated) to KeepConfiguration (LP: #1896799)

---

netplan_cli/cli/commands/apply.py
netplan_cli/cli/utils.py
tests/test_utils.py

NM is not bringing it back automatically after we flush its addresses. It's not clear if it's a bug or intended behavior.
It's bad because we have services listening on the loopback interface, such as resolved.
How to reproduce:
1. Install network-manager in Mantic and let it manage at least one of your interfaces
2. You'll see it's managing 'lo' automatically
3. Try to change the 'lo' connection, something like `nmcli con mod lo mtu 1500`
4. NM will emit a YAML (an nm-device) for 'lo'
5. Run `netplan apply`
6. You'll see that the 'lo' connection is down and the 'lo' interface has no IPs
As an alternative (was my original patch) we could just stop flushing 'lo', but that might be what the user want to do, because they can add extra addresses to it for example.
This might actually be a bug …

apply: bring "lo" back up if it's managed by NM (LP# 2034595)

---

src/parse-nm.c
tests/parser/test_keyfile.py

When the prefix is omitted for IPs in the allowed-ips list, we were appending a /32 to them without checking the address family.
IPv6 addresses will have a /128 appended to them if it's not present.
See LP#2046158

parse-nm/wg: append the correct prefix to IPv6 addresses (LP: #2046158)

---

src/openvswitch.c
tests/generator/base.py

With systemd 255, the ovs integration test is hitting this limit and the test fails due to that. As it's a oneshot service, it should be OK to disable this limit.
The alternative solution is to add a delay between each OVS integration test. In my tests, the required delay to get all the tests passing was 3 seconds. This change is to avoid increasing the time spent during tests.
LP bug: https://bugs.launchpad.net/ubuntu/+source/netplan.io/+bug/2047827
What do you think, Lukas?

ovs: disable StartLimitBurst in the ovs-cleanup service (LP: #2047827)

---

doc/conf.py
doc/contribute-docs.md
doc/dbus-config.md
doc/examples.md
doc/howto.md
doc/netplan-everywhere.md

This is a follow up to #429 -- don't merge before it.
Improve how-to docs:
- Move intro to how-to landing page
- Make headings consistently use "How to"
- Remove (post-build) "How to" from TOC
[FR-6139]: https://warthogs.atlassian.net/browse/FR-6139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix howto docs

---

src/error.c
src/meson.build
src/netplan.c
src/networkd.c
src/nm.c
src/openvswitch.c
src/parse-nm.c
src/parse.c
src/sriov.c
src/types-internal.h
src/types.c
src/util.c
src/validation.c
tests/ctests/meson.build
tests/ctests/test_netplan_error.c
tests/ctests/test_netplan_keyfile.c
tests/ctests/test_netplan_misc.c
tests/ctests/test_netplan_nm.c
tests/ctests/test_netplan_openvswitch.c
tests/ctests/test_netplan_parser.c
tests/ctests/test_netplan_state.c
tests/ctests/test_netplan_validation.c
tests/ctests/test_utils.h

With these changes, a copy of libnetplan without static functions will be build. All the test files will be linked against this separate library. With that, there is no need to include the C files in the test files anymore.
To make this possible, all the static keywords in function declarations were replaced with a macro that will be defined at compilation time.
My goal is to make #425 easier to be implemented. Also, refactoring the C code is less likely to break the build of test files...

ctests: stop including C files in the test files

---

doc/.custom_wordlist.txt
doc/explanation.md
doc/security.md

docs: add a topic about security

---

netplan_cli/cli/state_diff.py
tests/cli/test_state_diff.py

When an interface has multiple IPs in the same subnet, there will be host scoped routes for each of them and the "src" address will be one of the IPs for all of them.
The filtering of this type of route was not working properly and including the extra routes in the diff.
This change generalizes the verification to see if the destination address is one of the system own addresses instead of comparing it with the src address.
While here, fix the data structure passed to the filtering method. It should be a list but a dictionary was being passed to it.

state_diff: fix filtering of host scoped routes

---

netplan_cli/cli/sriov.py
tests/test_sriov.py

We are parsing all the configuration unnecessarily here. np_state is being overridden by the State instance from the config manager.
Fix a related unit test. The configuration is expected to fail but now it's failing in a different place and raising a different exception.

cli/sriov: remove unused code

---

src/sriov.c
tests/generator/base.py
tests/test_sriov.py

The `sriov-rebind.service` will have duplicates when multiple VFs are being created. See below:
```
$ cat run/systemd/system/netplan-sriov-rebind.service
[Unit]
Description=(Re-)bind SR-IOV Virtual Functions to their driver
After=network.target
After=sys-subsystem-net-devices-enp3s0f0np0.device
After=sys-subsystem-net-devices-enp3s0f0np0.device
After=sys-subsystem-net-devices-enp3s0f0np0.device
After=sys-subsystem-net-devices-enp3s0f1np1.device
After=sys-subsystem-net-devices-enp3s0f1np1.device
After=sys-subsystem-net-devices-enp3s0f1np1.device
[Service]
Type=oneshot
ExecStart=/usr/sbin/netplan rebind enp3s0f0np0 enp3s0f0np0 enp3s0f0np0 enp3s0f1np1 enp3s0f1np1 enp3s0f1np1
```

sriov: don't generate duplicate entries in the rebind.service file

---

netplan_cli/cli/commands/apply.py
netplan_cli/cli/ovs.py
netplan_cli/cli/utils.py
tests/test_utils.py

Made changes outlined in this bug
Credit:  @brianfinley https://launchpad.net/~finley
https://bugs.launchpad.net/ubuntu/+source/netplan.io/+bug/2041727 
Tested on Ubuntu 22.04.3 LTS and the error message no longer displays
```
@@ -414,4 +414,5 @@
if exit_on_error:
sys.exit(1)
except OvsDbServerNotRunning as e:
- logging.warning('Cannot call Open vSwitch: {}.'.format(e))
+ if utils.systemctl_is_active('ovsdb-server.service'):
+ logging.warning('Cannot call Open vSwitch: {}.'.format(e))
```
https://bugs.launchpad.net/ubuntu/+source/netplan.io/+bug/2041727

check if ovsdb-server.service is active before displaying warning

---

doc/netplan-yaml.md
src/networkd.c
src/nm.c
src/parse-nm.c
src/parse.c
src/util-internal.h
src/util.c
tests/generator/test_ethernets.py
tests/integration/ethernets.py
tests/parser/test_keyfile.py

Besides the actual MAC address value, Network Manager also accepts the following values: preserve, permanent, random and stable.
When set via NetworkManager, these special values would end up in the passthrough section. But if users try to set it manually, the parsing would fail.
This changes add support for these special values for the NetworkManager renderer and return an error if the user tries to use them with networkd.
Related to https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/2045096

parser: accept the special MAC address options (LP: #2045096)

---

.github/workflows/network-manager.yml

CI: fix NetworkManager autopkgtest not using deb822
See:
* https://bugs.launchpad.net/ubuntu/+source/autopkgtest/+bug/2052639
* https://salsa.debian.org/ci-team/autopkgtest/-/merge_requests/287

CI: fix NetworkManager autopkgtest not using deb822

---

doc/netplan-yaml.md
src/abi.h
src/netplan.c
src/networkd.c
src/nm.c
src/parse.c
src/types.c
tests/generator/test_tunnels.py
tests/integration/bridges.py

This MR adds additional bridge settings `hairpin` and `port-mac-learning` on bridge ports. They are useful when using VXLAN tunnels with e.g. FRR.
This is my first MR to netplan, I tried my best to run the tests locally first.

Add additional bridge port settings

---

netplan_cli/cli/core.py

Hi, while packaging netplan 0.107 for Azure Linux I ran into this small bug when running checks. This seems like the most trivial fix.
tl;dr: when python-rich is not present the logger will not be configured correctly. More specifically:
- The logging level will be `WARNING` instead of `INFO`
- Passing `--debug` has no effect.
When python-rich is not present, the import in [netplan_cli/cli/commands/status.py#L35](https://github.com/canonical/netplan/blob/45f7cd1569896d9e316c130bf5c60b7ccfc8211d/netplan_cli/cli/commands/status.py#L35) will fail, causing the `except` clause to run which calls `logging.debug(...)` in [netplan_cli/cli/commands/status.py#L47](https://github.com/canonical/netplan/blob/45f7cd1569896d9e316c130bf5c60b7ccfc8211d/netplan_cli/cli/commands/status.py#L47)
However, …

Fix logging setup when python-rich is not present

---

.github/workflows/autopkgtest.yml

See also: https://launchpad.net/~slyon/+archive/ubuntu/netplan-ci/+sourcepub/15854943/+listing-archive-extra
Backported meson 1.2 to gain `python.bytecompile`: https://github.com/mesonbuild/meson/pull/11530/commits/0e7fb07f915b7a2b04df209fbacd92aca19c87af

CI: adopt autopkgtest for 1.0-1 on 22.04

---

.github/workflows/snapd.patch
src/parse-nm.c
tests/parser/test_keyfile.py

Netplan doesn't support DNS options such as SNI. When we parse a nameserver entry with the SNI server name, example: 1.2.3.4#name.domain, the string is added to the list of nameservers without proper parsing/validation.
This is a workaround for LP#2055148.
Example:
```
[connection]
id=ethernet-eth123
uuid=572506e3-ab77-4c62-be96-b565984d90b3
type=ethernet
interface-name=eth123
[ethernet]
[ipv4]
dns=8.8.8.8;1.1.1.1#lxd;192.168.0.1#domain.local;
method=auto
[ipv6]
addr-gen-mode=default
dns=::1;abcd::1#domain.local;
method=auto
[proxy]
```
YAML without this patch:
```
$ LD_LIBRARY_PATH=build/src/ PYTHONPATH="$(pwd):$(pwd)/build/python-cffi"  python3 tools/keyfile_to_yaml.py /tmp/nm1.nmconnection
network:
version: 2
ethernets:
NM-572506e3-ab77-4c62-be96-b565984d90b3: …
```

parse-nm: add a workaround for the DoT DNS option (LP: #2055148)

---

.github/workflows/config-fuzzing.yml
tests/config_fuzzer/README.md
tests/config_fuzzer/index.js
tests/config_fuzzer/package.json
tests/config_fuzzer/runner.sh
tests/config_fuzzer/schemas/bonds.js
tests/config_fuzzer/schemas/bridges.js
tests/config_fuzzer/schemas/common.js
tests/config_fuzzer/schemas/dummy-devices.js
tests/config_fuzzer/schemas/ethernets.js
tests/config_fuzzer/schemas/modems.js
tests/config_fuzzer/schemas/nm-devices.js
tests/config_fuzzer/schemas/openvswitch.js
tests/config_fuzzer/schemas/tunnels.js
tests/config_fuzzer/schemas/virtual-ethernets.js
tests/config_fuzzer/schemas/vlans.js
tests/config_fuzzer/schemas/vrfs.js
tests/config_fuzzer/schemas/wifis.js

This is a project I've been working. It will use json schemas to generate random YAML files. It implements support for most of the interface types and properties support by Netplan. I used JavaScript (note that I don't have much experience with it :P) to use the [json-schema-faker](https://github.com/json-schema-faker/json-schema-faker) project.
The config_fuzzer will generate random netplan YAML files and use them to test libnetplan.
It also adds a new Github workflow to run the tests. If a crash or memory issue is detected, the workflow will fail in the end. It's being executed in this PR.
There is a lot of room for improvement but this is a good start.

tests: import the config fuzzing tests

---

src/parse.c
src/util-internal.h
src/util.c
tests/generator/test_bonds.py

Error out if an interface is declared as primary of multiple bonds. Besides being wrong it's causing a memory leak.
Found with https://github.com/daniloegea/netplan-fuzz
Test case:
```yaml
network:
version: 2
ethernets:
eno1: {}
bonds:
bond0:
parameters:
primary: eno1
bond1:
parameters:
primary: eno1
```
Result
```
$ ./build/src/generate --root-dir /tmp/fakeroot
=================================================================
==1732948==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 5 byte(s) in 1 object(s) allocated from:
#0 0x711093a8bb27 in malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
#1 0x711093794ed9 in g_malloc (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x62ed9) (BuildId: ab12e476c12cb3b1fbdd6b86b800846e3dd61000)
#2 0x7110937aa8a8 in g_strdup …
```

ATTN: parse/bonds: handle same primary in multiple bonds

---

src/parse.c
tests/generator/test_common.py

Options gateway4 and gateway6 were not being properly redefined when a merge happens. Redefinition was causing a crash due to an assert in the set_str_if_null macro.
While this assertion helped identifying the merge issue, I believe it's not the best place to keep it so I'm removing it from the macro and making the macro do only what it name suggests it does.
This macro is used in other places but this problem seems to not happen there as far as I can see.
Add a couple of unit test to check the merge is working.
Reproducer:
```yaml
network:
ethernets:
eth0:
addresses:
- 192.168.0.1/24
gateway4: 192.168.0.123
eth0:
gateway4: 192.168.0.111
```
```
$ netplan generate --root-dir /tmp/fakeroot4
** (generate:190262): WARNING **: 18:08:41.479: `gateway4` has been deprecated, use default routes …
```

parse: fix redefinition of gateway(4|6)

---

doc/.sphinx/requirements.txt
doc/creating-link-aggregation.md
doc/howto.md
doc/matching-interface-by-mac-address.md
doc/netplan-tutorial.md
doc/netplan-yaml.md
doc/tutorial.md
doc/using-static-ip-addresses.md

This PR revamps the Netplan tutorial:
- Some reorg for better flow.
- Extensive language and formatting improvements.
- Moves parts to 'how-to guides' where appropriate.
- Tutorial landing page improved.
In addition:
- How-to guides landing page slightly improved in structure (to be revisited).
- Minor lang. + mark-up fixes in YAML reference.
Fixes [FR-2811](https://warthogs.atlassian.net/browse/FR-2811).
[FR-2811]: https://warthogs.atlassian.net/browse/FR-2811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Tutorial improvements

---

netplan_cli/cli/commands/generate.py
netplan_cli/cli/utils.py
src/generate.c
src/networkd.c
src/networkd.h
src/util.c
tests/cli_legacy.py
tests/ctests/meson.build
tests/ctests/test_netplan_networkd.c
tests/generator/base.py
tests/generator/test_args.py
tests/generator/test_common.py
tests/integration/ethernets.py
tests/test_utils.py

Skip s-n-wait-online if we don't have any non-optional interfaces, using a "ConditionPathIsSymbolicLink=" checking Netplan's s-n-wait-online.service enablement symlink.
This is in favor to RequiredForOnline=yes as the behavior of upstream (pure)
systemd-networkd-wait-online.service is not mean to be used in this way.
If "RequiredForOnline=no" sd-networkd-wait-online will fully ignore the
corresponding interface and it will block/delay network-online.target if
no interfaces are "RequiredForOnline=yes" at all.
FR-7246
Note: This is a replacement for https://github.com/canonical/netplan/pull/455 that keeps compatibility with cloud-init, so it can still sort `After=systemd-networkd-wait-online.service` AND `Before=network-online.target`.

Create custom systemd-networkd-wait-online.service override to wait on individual interfaces. (LP: #2060311)

---

netplan_cli/__init__.py
python-cffi/netplan/__init__.py

python: elements of __all__ must be strings

---

doc/explanation.md
doc/generator.md
doc/netplan-generate.md
include/parse.h
include/types.h
python-cffi/netplan/__init__.py
python-cffi/netplan/_build_cffi.py
python-cffi/netplan/_utils.py
python-cffi/netplan/parser.py
src/generate.c
src/networkd.c
src/nm.c
src/parse.c
src/types-internal.h
src/util.c
src/validation.c
tests/config_fuzzer/runner.sh
tests/ctests/test_netplan_parser.c
tests/generator/base.py
tests/generator/test_errors.py
tests/integration/dbus.py
tests/integration/run.py
tests/test_libnetplan.py

This is an implementation of what I called "parser flags". The idea is to enable the user to change some parsing decisions.
The main application at the moment is to support ignoring parsing errors. Currently Netplan will not generate any configuration if a little mistake is made in one of its YAML files. It can be really bad if you're operating a remote system and end up rebooting the system with a syntax issue in one of your files. Your system will basically boot without any network configuration.
The IGNORE_ERRORS flag will allow the Netplan generator to ignore bad files and bad netdefs so it will still generate some configuration.
**TESTS**
Integration tests will be executed twice now, once without the ignore_errors flags and once with it enabled. It's intended to increase the …

Ignore bad NetDefs and files via parser flags

---

.github/workflows/debci.yml

Meson migration is stuck, blocking Netplan migration in Debian.
See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1059223

CI: Fix DebCI check, using newer 'meson' from unstable

---

tests/integration/diff.py

The syntax used to add a link seems to now work anymore with the latest iproute2.

tests: fix diff test with iproute2 6.8

---

netplan_cli/cli/commands/generate.py

When --mapping is used, nothing is generated so there is no need for calling daemon-reload.

cli/generate: skip daemon_reload with --mapping

---

tests/ctests/test_netplan_parser.c

The error object wasn't being released.

ctests: fix a memory leak in a unit test

---

src/networkd.c
src/nm.c
tests/generator/test_errors.py

These problems happen when the ignore_errors flag is used.
Wifi: When parsing is interrupted before access points are added to the interface, the code that generates configuration for NM and networkd will crash. They assume the list is never empty. Add a check to see if the list is empty.
Wireguard: The same problem happens on networkd when the list of peers is empty. The NM code already checks it.
Add unit tests for these cases.

nm/nd: fix a couple of crashes

---

netplan_cli/cli/commands/migrate.py
tests/cli_legacy.py

Netplan migrate haven't supported old syntax network interface aliases yet (eg. eth1:1 alias for eth1). An if statement is added to migrate.py that checks if interface name contains ':', this case the iface will be renamed and handled as not the alias one. The expected output is a simple interface that has multiple addresses. A test case is also provided in cli_legacy.py with the following name: test_static_ipv4_alias.

migrate: support aliases

---

README.md
doc/contribute-docs.md
doc/netplan-yaml.md

modified the doc/contribute-docs.md file to include information about building the documentation locally and other information to successfully contribute to the documentation

added guide for contributing to the netplan documentation

---

include/netdef.h
netplan_cli/cli/commands/status.py
netplan_cli/cli/state.py
netplan_cli/cli/state_diff.py
python-cffi/netplan/_build_cffi.py
python-cffi/netplan/netdef.py
src/util-internal.h
src/util.c
tests/cli/test_state.py
tests/cli/test_state_diff.py
tests/cli/test_status.py
tests/test_libnetplan.py

This PR contains a bunch of small improvements to `netplan status --diff` and some additions to the libnetplan API:
- Add getters for the `gateway4` and `gateway6` properties. This is required during the analysis of routes.
- Routes from `gateway4` and `gateway6` are added to the list of routes being analyzed.
- Make use of the property `dynamic` from `addr_info` to help determining if the address was received dynamically.
- Make use of the `ra` flag from routes to help finding IPs that were received via RA.
- Add getter for the `accept-ra` property.
- Improve the analysis of RA and LL addresses.
- Fix a rendering issue in the `--diff` mode when `python3-rich` is not present.
- Use the ConfigSource property from networkd to reduce the guessing and be more precise when analyzing dynamic …

netplan status --diff fixes and improvements

---

netplan_cli/cli/commands/apply.py

This PR fixes these two problems:
* ~It restarts networkd instead of reload/reconfigure
Due to systemd-networkd bugs, reload/reconfigure was not working in
some cases. Instead, restart the service if the configuration has
changed (LP#2058976).~
- It compares full configuration to decide to restart or not networkd.
Copy the current networkd configuration and then call generate so we
know more accurately if systemd-networkd needs to be restarted.

apply: make sure that networkd is restarted when needed

---

doc/netplan-generate.md

There was a single bullet point that divided a sentence. I removed it because I thought it was a typo.

bullet point removal

---

src/yaml-helpers.h
tests/ctests/test_netplan_keyfile.c

The YAML emitter from libyaml will convert non-ascii characters to latin1 by default.
See LP: #2071652
See https://bugs.launchpad.net/netplan/+bug/2071652 for details.

emitter: allow unicode characters in the emitter (LP: #2071652)

---

src/networkd.c
tests/generator/test_args.py
tests/integration/ethernets.py

wait-online: wait for 'routable' state, if corresponding IPs are defined
Generally, we should be waiting on "routable" state (instead of "degraded") when we have static IP/dhcp4/dhcp6/RA.
[Our spec](https://discourse.ubuntu.com/t/spec-definition-of-an-online-system/27838) defines "at least one interface MUST be up on the link layer and have received layer 3 (IP) configuration" (ignoring link-local).
We now start two separate `systemd-networkd-wait-online` processes. One waiting for "carrier" & "degraded" interfaces (including the "routable" ones), not using "--any". Another one waiting just for "routable" interfaces, combined with "--any". Both blocking "network-online.target".
FR-7838

networkd: make s-n-wait-online wait for at least one routable interface

---

netplan_cli/cli/commands/apply.py
tests/netplan_dbus/test_dbus.py

CLI:apply: call udevadm trigger, using --action=add (Closes: #1071220)
This will (re)-apply .link files, e.g. to set offloading options
As per discussion in [Debian#1071220](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1071220):
Yu says:
> https://github.com/canonical/netplan/blob/26d2591d771cb4343c06dbb1e0eb1f3587ec910d/netplan_cli/cli/commands/apply.py#L257
> 
> Here, "--action add" is necessary, otherwise the generated .link
> files will be never applied to existing interfaces.

CLI:apply: call udevadm trigger, using --action=move (Closes: #1071220) (LP: #2066344, LP: #2071363)

---

.github/workflows/autopkgtest.yml
doc/examples.md
doc/netplan-yaml.md
examples/static-routes.yaml
python-cffi/netplan/_build_cffi.py
python-cffi/netplan/netdef.py
src/netplan.c
src/networkd.c
src/nm.c
src/parse-nm.c
src/parse.c
src/types-internal.h
tests/config_fuzzer/schemas/common.js
tests/generator/test_routing.py
tests/integration/routing.py
tests/parser/test_keyfile.py
tests/test_libnetplan.py

Hello everybody. I was missing the [advmss](https://www.linux.org/docs/man8/ip-route.html) functionality for static routes, and I decided to implement it. This option has been tested successfully in systemd-networkd, but has not tested in network manager.
Param name for ip route: advmss
Param name for systemd networkd: TCPAdvertisedMaximumSegmentSize
Param name for network manager: advmss

Implementing advmss ip route option

---

netplan_cli/cli/commands/apply.py
netplan_cli/cli/commands/generate.py
rpm/netplan.spec
src/generate.c

The udev rules directories are monitored and re-loaded automatically with modern systemd-udevd. No need to manually reload them in the generator, causing side-effects.
We can still force-reload them when issuing `netplan generate` or `netplan apply` through the CLI, just to be on the safe side.
Replaces: https://github.com/canonical/netplan/pull/304

generate: avoid calling 'udevadm control --reload' (LP: #1999178)

---

.github/workflows/debci.yml
meson.build
meson_options.txt
src/meson.build

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1071599
FR-8335

meson: Add 'testing' option

---

.github/workflows/automatic-doc-checks.yml

Updates the docs-check GH Action runner to `ubuntu-latest` to fix a [problem with Doxygen](https://github.com/canonical/netplan/actions/runs/10351751575/job/28650924351).
(Actual spelling mistakes fixed in #499.)
n/a

Update the docs checks runner to ubuntu-latest

---

.github/workflows/tiobe.yml
meson.build

I found out that this https://github.com/canonical/netplan/pull/496 is not really required. TICS will not use `-Wconversion` by default.

Add a scheduled workflow to run TICS

---

.github/workflows/tiobe.yml

Fix the job name and disable the scheduler for now so the job can be triggered manually [1].
[1] - https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch

ci: run meson tests with unbuffer

---

.github/workflows/tiobe.yml

"unbuffer" is installed by it.

ci/tics: install "expect" as a dependency

---

src/nm.c
tests/parser/test_keyfile.py

Dummy connections (from my testing) are not being passed the `ipv4.route-metric` value from NM, instead they have the default value of 550, though this behavior was not observed with the IPv6 protocol. The change is to allow to pass `ipv4.route-metric` to NM if either `dhcp4: True` or `ipv4.route-metric` values are passed using a `method: manual` setup.
This was tested by cloning the repo, making the code change and following [build install instructions](https://github.com/canonical/netplan?tab=readme-ov-file#build-using-meson).
You can also re-create this by running the following commands.
- Run`nmcli c a type dummy ifname pvpnksintrf0 con-name pvpn-killswitch ipv4.method manual ipv4.addresses "100.85.0.1/24" ipv4.gateway "100.85.0.1" ipv6.method manual ipv6.addresses …

netplan ignores NetworkManager ipv4.route-metric (LP: #2076172)

---

src/util.c

Change default umask when creating dirctories (LP: #2076319)

---

.github/workflows/autopkgtest.yml
.github/workflows/build-abi.yml
.github/workflows/check-address-sanitizer.yml
.github/workflows/check-coverage.yml
.github/workflows/check-wording.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/config-fuzzing.yml
.github/workflows/coverity.yml
.github/workflows/debci.yml
.github/workflows/network-manager.yml
.github/workflows/snapd.patch
.github/workflows/spread.yml
src/networkd.c

Move to Ubuntu 24.04 and drop the workarounds that were needed to run the tests on 22.04.
Note: I mistakenly thought it was already available after finding some github action commits adding Noble to the list of runners. But it's still in the roadmap https://github.com/github/roadmap/issues/958

ci: migrate to Ubuntu 24.04

---

.github/workflows/tiobe.yml

The download started to fail without authentication.
I tested it locally and the script `install_tics.sh` works when the variable is exported.

ci/tics: set the token before trying to download TICS

---

src/generate.c
src/netplan.c
src/networkd.c
src/nm.c
src/openvswitch.c
src/parse-nm.c
src/parse.c
src/sriov.c
src/types.c
src/util.c

Fix some warnings reported by TiCS
* (6.8.4.b) Expression 'rootdir' is not a proper 'Boolean' condition.
* (6.10.8.b) Reserved identifier `__FUNCTION__` may not be used.
* (6.3.2.3.d) Encountered conversion between boolean type '(0, 1)' and non-boolean type 'char *'.

Several code cleanup & fixes for TiCS

---

tests/integration/base.py
tests/integration/ethernets.py

These tests validate the Stable Privacy and Modified EUI-64 IPv6 address generation methods under both NetworkManager and systemd-networkd.

tests: ethernets: Add ipv6-address-generation integration tests

---

.github/workflows/autopkgtest.yml
.github/workflows/debci.yml
netplan_cli/cli/commands/apply.py
netplan_cli/cli/sriov.py
netplan_cli/cli/utils.py
tests/cli/test_units.py
tests/test_sriov.py
tests/test_utils.py

netifaces doesn't return the permanent MAC address of physical interfaces.
This causes a problem with bonds for example where all the interfaces in the bond will share the same MAC address. When `netplan apply` tries to find a unique matching based on the MAC returned by netifaces and the MAC set in the YAML, it will not be found.
```
[]
Cannot find unique matching interface for nic0
```
The `is_composite_member()` method wasn't working properly as well. It was always returning False. In the end I stopped using it.
Regarding skipping bond/bridge members during renames, that seems to be put in place as a workaround for [LP: #1802322](https://bugs.launchpad.net/netplan/+bug/1802322). The problem it fixed was happening because the code was matching interfaces by their non-permanent MAC …

cli: drop python-netifaces (LP: #2065870, LP: #2017585)

---

include/types.h
src/parse-nm.c

The new types DUMMY and VETH were added to the types enum after the generic type NM. We it checked if the interfaces was virtual, in order to build the netdef id, it wouldn't consider DUMMY and VETH.
Because of that, when a dummy or veth interface is created via network manager, it's netdef ID would be the connection UUID. For virtual devices we want it to be the interface name.
It works fine with existing interfaces. Network Manager will get the netdef ID from the file name. It was tested by creating a bunch of dummies and veths via nmcli, updating libnetplan and creating new and modifying existing connections.
I created a PPA for oracular with this patch here https://launchpad.net/~danilogondolfo/+archive/ubuntu/netplan.io
Loading this keyfile:
```
[connection]
id=dummy-dummy0 …
```

parse-nm: account for veth and dummy when checking for virtual types

---

.github/workflows/autopkgtest.yml
.github/workflows/network-manager.yml
tests/integration/routing.py
tests/integration/tunnels.py

* Dropping some quirks that are not needed anymore as of the v1.1 packaging.
* Re-enable testing for network devices that need additional kernel modules (like `vrf` or `wireguard`) in containers.

CI: cleanup after v1.1 release

---

tests/integration/ethernets.py

Avoid flaky `test_ip6_eui64` results, when statefull DHCPv6 is quicker than stateless EUI-64 address generation.
Also use a `ra-stateless` configuration option to dnsmasq, to avoid providing stateful DHCP addresses to the client;
`ra-only` doesn't seem to work properly, when combined with `--dhcp-range` (from `integration/base.py`).
This seems to fail from time to time on systemd v256 based systems, such as Debian testing or Ubuntu oracular.
Follow-up to https://github.com/canonical/netplan/pull/509

tests:ethernets: avoid flaky test_ip6_eui64 results

---

.github/workflows/autopkgtest.yml
tests/integration/run.py

CI:tests: Disable NETPLAN_PARSER_IGNORE_ERRORS by default
It's taking lots of compute time in upstream and downstream CI systems.
We still keep it on inside our `autopkgtest.yml` CI test, but turn it off
by default otherwise.

[RFC] CI: Ignore errors off by default

---

netplan_cli/cli/ovs.py
src/openvswitch.c
tests/generator/base.py
tests/generator/test_ovs.py
tests/integration/ovs.py
tests/test_ovs.py

For complex values, ovs-vsctl requires that they are quoted or it will error out. [LP: #2070318](https://bugs.launchpad.net/netplan/+bug/2070318)
Interestingly, it seems to work from systemd units. But I added quotes there too.
I added a new test case to the integration test `test_settings_tag_cleanup` that will fail without quotes. It's based on the example provided in the bug report.
```
test_settings_tag_cleanup (__main__.TestOVS.test_settings_tag_cleanup) ... eth42 eth43 ovs0 ovs1
** (process:6306): WARNING **: 11:04:05.201: Permissions for /etc/netplan/01-main.yaml are too open. Netplan configuration should NOT be accessible by others.
ovs-vsctl: card-serial-number=MT42424242N8,enable-chassis-as-gw: unexpected "=" parsing set of 1 or more strings …
```

ovs: quote external-ids and other-config values (LP: #2070318)

---

meson.build
src/error.c
src/netplan.c
src/nm.c
src/openvswitch.c
src/parse-nm.c
src/parse.c
src/sriov.c
src/types-internal.h
src/util-internal.h
src/util.c
src/validation.c
src/yaml-helpers.h
tests/ctests/test_netplan_error.c
tests/ctests/test_netplan_keyfile.c
tests/ctests/test_netplan_parser.c

Fix some type conversions and make some implicit conversions explicit.
It's a requirement to add the TIOBE analysis to our CI as it will build the project with `-Wconversion`.
I'd recommend to use interactive rebase to step through each commit individually starting from the first one and call `meson compile` with `-j1` so you can see what compiler errors each commit fixes. I didn't want to paste the error to the commit messages...

Handle implicity conversions

---

doc/security.md
src/networkd.c
src/openvswitch.c
src/sriov.c
tests/generator/test_auth.py
tests/generator/test_wifis.py
tests/integration/base.py

networkd:openvswitch:sriov: Permissive umask for .service units (LP#2072486)
Writing world-inaccessible config files doesn't help when the data can still be accessed by any local user through the systemd APIs, e.g.: `systemctl show UNIT_NAME.service`
Using `640` permission on such .service unit files provides a false illusion of security and leads to systemd warnings in the journal, like this:
```systemd[1]: Configuration file /run/systemd/system/netplan-ovs-cleanup.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.```
Also:
* Update tests according
* Update doc/tread model accordingly
FR-8238

Use more permissive umask for .service units (LP: #2072486)

---

netplan_cli/cli/commands/apply.py

This PR essentially reverts https://github.com/canonical/netplan/pull/449/
The only conflict was due to an import that was removed (netifaces).
On https://github.com/canonical/netplan/pull/449/ `netplan apply` was changed to only apply if there were changes in the backend config files.
While this is a nice approach to avoid unnecessary network disruptions, backend configuration can be generated without `apply` be aware of it (via the generator (such as when daemon-reload is called) or `netplan generate`).
In this cases (if the generator or `netplan generate` runs first), when `apply` compares the previous configuration with the new one, there will be no changes.
See [LP: #2078009](https://bugs.launchpad.net/netplan/+bug/2078009). Here, when a new interface is added to the container, a …

Revert PR 449 (LP: #2078009)

---

src/networkd.c
tests/generator/base.py

Add an ExecReload command to call "wpa_cli reconfigure" on the interface. With that we can use "systemctl reload" to reconfigure a wireless device without having to call stop/start.

wpa_supplicant: add ExecReload to the service unit

---

doc/netplan-yaml.md
src/parse.c
src/util-internal.h
src/util.c
tests/generator/test_ethernets.py
tests/generator/test_wifis.py
tests/integration/wifi.py

802-11-wireless.cloned-mac-address = stable-ssid was added in Network Manager 1.46 and is available through the GUI applet.
Fixes https://bugs.launchpad.net/ubuntu/+source/netplan.io/+bug/2084234

networkmanager: add support for stable-ssid MAC option (LP: #2084234)

---

.github/workflows/rpmbuild.yml
src/parse.c

Ignore debuginfo packages in our local CI to avoid this error:
```
Processing files: netplan-debugsource-0.106-0.fc41.x86_64 error: Empty %files file /home/test/rpmbuild/BUILD/netplan-0.106-build/netplan-0.106/debugsourcefiles.list
Empty %files file /home/test/rpmbuild/BUILD/netplan-0.106-build/netplan-0.106/debugsourcefiles.list
```

CI: Fix fedora:latest (F41) failure

---

doc/netplan-yaml.md
src/nm.c
src/validation.c
tests/generator/test_routing.py
tests/generator/test_vrfs.py
tests/integration/routing.py

NetworkManager supports ip rules via the "routing-ruleX" field.  Let's teach the networkmanager backend to emit "routing-ruleX" entries for each "routing-policy" entry in the netplan yaml.
For example, the following netplan configuration snippet:
```
eth0:
addresses:
- "10.1.2.3/24"
routing-policy:
- to: 8.7.6.5
table: 254
priority: 10
- to: 1.2.3.4
from: 8.7.6.5
table: 253
mark: 18
type-of-service: 4
priority: 11
```
..should generate something like the following in the NetworkManager configuration:
```
[ipv4]
method=manual
address1=10.1.2.3/24
routing-rule1=to 8.7.6.5 table 254 priority 10
routing-rule2=from 8.7.6.5 to 1.2.3.4 tos 4 fwmark 18 table 253 priority 11
```
- https://bugs.launchpad.net/netplan/+bug/2086544

networkmanager: add support for "routing-policy" (LP: #2086544)

---

doc/netplan-yaml.md

Would be nice for this to be a link instead of a code snippet.

doc: Add anchor link for deprecated gateway4/6 keys

---

src/parse.c

When we process a nm-device we check to see if the renderer is NetworkManager. If it's not set to NetworkManager we log a warning message and change the backend.
This verification can be only done after the netdef is processed. Move the verification so it happens after the call to process_mapping().
Fixes LP: #2091755
Reproducer:
```yaml
network:
version: 2
nm-devices:
NM-db5f0f67-1f4c-4d59-8ab8-3d278389cf87:
networkmanager:
uuid: "db5f0f67-1f4c-4d59-8ab8-3d278389cf87"
name: "myvpnconnection"
passthrough:
connection.type: "vpn"
```
```
$ netplan --debug get --root-dir /tmp/fakeroot
** (process:70728): DEBUG: 15:57:33.741: starting new processing pass
** (process:70728): DEBUG: 15:57:33.741: netplan: NM-db5f0f67-1f4c-4d59-8ab8-3d278389cf87: handling NetworkManager …
```

parse: fix renderer validation for nm-devices (LP: #2091755)

---

.github/workflows/spread.yml

Cleanup `spread.yml` workflow now that https://github.com/canonical/spread/pull/184 is fixed

CI: cleanup spread.yml workflow

---

netplan_cli/cli/commands/apply.py

Fixes LP: [#2095203](https://bugs.launchpad.net/netplan/+bug/2095203)
This is a first draft to get the discussion going as requested in the LP. Based on the `udevadm` teardown from the [related snapd PR](https://github.com/canonical/snapd/pull/11056#pullrequestreview-806332045), I think this is very unlikely to cause a regression.

cli:apply: Ignore udevadm errors triggering devices (LP: #2095203)

---

.github/workflows/autopkgtest.yml
.github/workflows/network-manager.yml
tests/integration/base.py
tests/integration/regressions.py
tests/integration/wifi.py

* [tests:wifi: use dhcpcd istead of deprecated ISC dhclient](https://github.com/canonical/netplan/pull/541/commits/85402e3d7340043cb65434fa6bc2030703faa921)
We cannot rely blindly on ISC `dhclient` (which is deprecated and not pre-installed in Ubuntu anymore) leading to failures, like:
```
2315s ======================================================================
2315s ERROR: test_wifi_ap_open (__main__.TestNetworkManager.test_wifi_ap_open)
2315s ----------------------------------------------------------------------
2315s Traceback (most recent call last):
2315s   File "/tmp/autopkgtest.M08ut1/build.PMg/src/tests/integration/wifi.py", line 175, in test_wifi_ap_open
2315s     out = subprocess.check_output(['dhclient', '-1', '-v', self.dev_w_ap],
2315s …
```

tests:wifi: Replace deprecated ISC dhclient & fail properly

---

.github/workflows/autopkgtest.yml
.github/workflows/network-manager.yml
src/networkd.c
tests/generator/test_args.py
tests/integration/ethernets.py

networkd: wait-online wait for DNS servers to be assigned
As implemented in systemd (v258):
https://github.com/systemd/systemd/pull/34640
Spec: https://discourse.ubuntu.com/t/spec-definition-of-an-online-system/27838
Follow-up to: https://github.com/canonical/netplan/pull/482 https://github.com/canonical/netplan/pull/456

Utilize sd-nd-wait-online for waiting on DNS servers

---

include/parse.h
include/state.h

The state.h and parse.h files are part of the public api of libnetplan. These function prototypes declared there should adhere the c-standard.
Function prototypes for functions that don't take any parameters should have `void` as the parameter list. Function prototypes with an empty parameter list are treated by the compiler as accepting any arbitrary parameter.

Fix function prototypes for *_new() functions of parser and state

---

meson.build
netplan_cli/cli/ovs.py
src/openvswitch.c
src/openvswitch.h
src/util-internal.h
src/validation.c
tests/cli/test_get_set.py
tests/generator/base.py
tests/generator/test_ovs.py
tests/integration/ovs.py
tests/test_configmanager.py
tests/test_libnetplan.py
tests/test_ovs.py

Changes the checks to be based around the availability of the command line OVS tools instead of the availability of the service installed under apt. This allows netplan to consume OVS when it is provided as part of another package such as in snap environments.
This involves minor changes to lots of the OVS code and also modifies the unit tests as to handle OVS from both standard and nonstandard setups.

Allows non standard OVS setups

---

netplan_cli/cli/commands/try_command.py
netplan_cli/configmanager.py
src/dbus.c
src/generate.c
src/util.c
tests/generator/base.py
tests/generator/test_args.py
tests/integration/base.py
tests/integration/scenarios.py
tests/test_configmanager.py

Fixes [LP#2083029](https://bugs.launchpad.net/netplan/+bug/2083029)
When using `systemd-networkd` as a backend, `netplan try` backs up `/run/systemd/network` before applying the new configuration. If the user fails to confirm the new configuration before the timeout is up, Netplan restores the old configuration by moving the backup into `/run/systemd/network` and invokes `networkctl reload` to apply the known-good configuration.
However, `networkd` will not/cannot read config files if their ownership is not `root:systemd-network`.
In effect, `netplan try` does not revert network changes _at all_ when using `networkd`.
Additionally, following the Ubuntu patches to NetworkManager in 23.10 (see [netplan everywhere](https://netplan.readthedocs.io/en/stable/netplan-everywhere/)), `netplan …

Fix `netplan try` revert (LP: #2083029)

---

.github/workflows/codeql-analysis.yml
.github/workflows/rpmbuild.yml
meson.build
python-cffi/netplan/meson.build
rpm/netplan.spec

Building a `/usr/lib/python3/dist-packages/netplan/_netplan_cffi.abi3.so` binary module for `python3-netplan` (instead of  `_netplan_cffi.cpython-311-x86_64-linux-gnu.so`/`_netplan_cffi.cpython-312-x86_64-linux-gnu.so`), making transitions and increasing Python compatibility.
This requires meson >= 1.3.0

meson: Build using Python 3.10 limited API (LP: #2050881)

---

netplan_cli/cli/state.py
netplan_cli/cli/utils.py
tests/cli/test_status.py
tests/test_utils.py

This patch makes the failure case of `netplan status` cleaner when systemd-networkd is not present.  This is at least relevant to Fedora/EPEL use-cases.
Before:
```
[root@alma-9-srpm-test 1.el9]# netplan status
Failed to start systemd-networkd.service: Unit systemd-networkd.service not found.
File "/usr/sbin/netplan", line 23, in <module>
netplan.main()
File "/usr/share/netplan/netplan_cli/cli/core.py", line 58, in main
self.run_command()
File "/usr/share/netplan/netplan_cli/cli/utils.py", line 332, in run_command
self.func()
File "/usr/share/netplan/netplan_cli/cli/commands/status.py", line 77, in run
self.run_command()
File "/usr/share/netplan/netplan_cli/cli/utils.py", line 332, in run_command
self.func()
File …
```

Fail cleanly when systemd-networkd is not installed

---

tests/netplan_dbus/test_dbus.py

test:dbus: avoid dependency on dbus-launch (Closes: #1117099)

test:dbus: avoid dependency on dbus-launch (Closes: #1117099)
