canonical/netplan

Makefile
Rework the Makefile to handle supporting different file system layouts across a variety of distributions, especially merged-usr vs split-usr filesystems. Now all file system paths can be trivially overridden from the `make` invocation.
In addition, path detection via `pkg-config` is used for `bash-completion`, with a fallback to `/etc/bash_completion.d/` in the event the Makefile cannot probe for the correct path.
The symlinks made are now relative to `DESTDIR`, and `DESTDIR` is now consistently used everywhere.
Finally, the Python code linting program detection has been extended slightly to support the executable file names used in Fedora/Mageia/openSUSE in addition to the Debian/Ubuntu ones.
Signed-off-by: Neal Gompa <ngompa13@gmail.com>
=> Rework the Makefile to be more distribution-agnostic and easier to override

.github/pull_request_template.md
Just updating the PR template, this should have no impact on anything else...
=> Use markdown for make check verbs

src/parse.c
I tried to be clever for a while and then stopped.
=> remove duplication of link handlers

doc/netplan.md
This simply clarifies the docs further, inspired by [LP: #1791363](https://bugs.launchpad.net/netplan/+bug/1791363) and what I've learned about NM (see [LP: #1769550](https://bugs.launchpad.net/netplan/+bug/1769550)) 
doc change only
=> Make MTU and MAC docs and example slightly clearer

netplan/cli/commands/apply.py
set-name applies only to physical interfaces.  physical interfaces which
are part of a bond or bridge may undergo a mac address change due to how
composition works.  Netplan cannot know if the current mac of the interface
is in fact the correct mac address and should instead skip renaming interfaces
that  are part of a composite device.
LP: #1802322
=> apply: skip non-physical and bond interfaces when applying name changes

snap/snapcraft.yaml
A snap is a bundle of your app and its dependencies that works without modification across Linux.
Snaps are discoverable and installable from the Snap store.e
=> [snap] Add 'snap/snapcraft.yaml'

debian/changelog, debian/postinst, netplan/cli/commands/ip.py
Not 100% sure this is the ideal direction to go in but I've uploaded it as I wanted to un-break debootstrap.
=> Fix debootstrap

doc/netplan.md
Revise documentation for clarity. This is a work in progress.
- [n/a] Runs `make check` successfully.
- [n/a] Retains 100% code coverage (`make check-coverage`).
- [n/a] \(Optional\) Closes an open bug in Launchpad.
=> (WIP) Revise documentation for clarity

netplan/cli/commands/apply.py
We were not re-starting networkd/NetworkManager in the case we moved
from a configuration that created netplan files in /run to one that did
not need files there. Now we make sure we re-start the services also in
that case, by checking if there were configuration files before the
generation step. Fixes LP: #1811868.
=> apply: re-start services also when unconfiguring

doc/netplan.md, src/networkd.c, src/parse.c, src/parse.h, tests/generator/test_dhcp_overrides.py
Add support to UseDomains dhcp-override option.
There are test not working, but there test fail on master branch
Same previous check
=> Use domains

doc/netplan.md, src/parse.h
Include feature flags in doc.
- [n/a] \(Optional\) Closes an open bug in Launchpad.
=> Add feature flags for new use-domains and ipv6 mtubytes features

examples/direct_connect_gateway_ipv6.yaml
Just adding an example for a directly-connected gateway on ipv6, mirroring planned changes on the webpage.
=> Add example for a directly-connected gateway on IPv6.

.github/workflows/check-coverage.yml
Run unit tests on each commit push or pull request. Upload coverage to Codecov to have the diff checked.
=> Use Github Actions for unit tests and Codecov upload

.github/workflows/build.yml, README.md
=> Update README badges

README.md, rpm/netplan.spec, snap/snapcraft.yaml
=> Update Github URL

tests/integration/base.py
=> tests:integration: cleanup OVS/WPA files

netplan/cli/commands/apply.py, netplan/cli/commands/generate.py, tests/dbus/test_dbus.py
Improve test coverage and handle additional error cases.
This is a follow-up for #208 wrt. https://github.com/snapcore/snapd/pull/10212
=> cli: SNAP special handling: improve test coverage and error handling

src/parse.c
When we do multi-pass parsing, we sometimes duplicate string without
freeing the previous one. This macro allows us to avoid said
duplication.
The commit uses the macro in a couple of places, but there are a lot of
other sites where it might be useful.
=> parse: new macro set_str_if_null to avoid duplicating existing fields

src/parse.c
This patch reworks the single route processing to only append the parsed
route to the interface when it has been fully validated, and use a
single error path otherwise. This allows us to locally control the
cleanup and freeing of the allocated route.
The previous version could indeed leak if process_mapping returned an
error (and that's assuming that the interface cleanup process would free
up the routes already assigned, which I haven't checked).
=> parse: handle_routes: clean up the route on error

doc/howto.md, doc/netplan-everywhere.md
=> docs: Add a short netplan-everywhere howto

doc/CODE_OF_CONDUCT.md
Add Ubuntu Code of Conduct 2.0
=> doc: Add Ubuntu Code of Conduct 2.0

tests/integration/regressions.py
Add autopkgtest for LP#1959570
=> tests: Add autopkgtest for LP#1959570

doc/netplan-everywhere.md
Dropping the PPA parts and update the workflow for Ubuntu 23.10, in preparation for an upcoming blog post.
=> doc: Update 'Netplan everywhere' for 23.10

.github/workflows/coverity.yml
=> workflow/coverity: install missing dependencies

doc/netplan-yaml.md
=> Fix wrong syntax in example

.github/workflows/spread.yml, spread.yaml
CI: fork spread to get #179 fixes
See https://github.com/snapcore/spread/pull/179
=> CI: fork spread to get #179 fixes

SECURITY.md
Add initial SECURITY.md policy
=> Add initial SECURITY.md policy

tests/integration/base.py, tests/integration/ethernets.py
test:integration: Try to improve test flakyness (Closes: #1069871)
=> test:integration: Try to improve test flakyness (Closes: #1069871)

.github/workflows/codeql-analysis.yml
This is needed after switching default token permissions to be restrictive by default. https://github.com/github/codeql/issues/8843
=> CI: fix CodeQL permissions

doc/netplan-tutorial.md
=> Add netplan try to netplan tutorial

.github/workflows/tiobe.yml
I executed it manually one last time to check it's working https://github.com/canonical/netplan/actions/runs/10404923276
=> ci: enable the TICS workflow scheduled task

tests/integration/wifi.py
=> tests: add integration test for wifi/psk-sha256

.github/workflows/autopkgtest.yml, .github/workflows/network-manager.yml, rpm/netplan.spec
=> CI: adopt to autopkgtest 5.47~24.04.1
